### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by LWisteria** [fixstars/clpy#10]
There's no CI in current version...

**Comment by ghost** [comment]
要件

* *New Primary* と *New Secondary* (非公開)でスクリプトを回せる
* Pull-request が来たら fork 先のブランチを見て CI できる

調査・検討

* Travis の local runner のようなものはあるか
    * Travis のドキュメントを一通り見たが見当たらず
* CircleCI の local runner はあるか
    * ちょっと目的は違うがあるにはある
* ほかに worker を切り離せる (無料) CI があるか
* Jenkins を動かす方法
* push を hook して In-house GitLab へ pull する方法
    * 結果の提示・pr への対応が難しい?

**Comment by ghost** [comment]
### GitHub の push をフックする
* [Hubot](https://hubot.github.com/) を立てておくと、GitHub から webhook を受け取ってシェルスクリプトを叩ける
    * ポート公開が必要。 [自前ホストHubotの参考](https://blog.odoruinu.net/2014/07/08/how-to-integrate-self-hosted-hubot-with-slack/)

**Comment by nsakabe-fixstars** [comment]
### Travis CI のバックエンドを変える
→ [Travis CI Enterprise](https://docs.travis-ci.com/user/enterprise/)

> **Hosted on your infrastructure** : Travis CI Enterprise supports the cloud or on-premises environment of your choice. This includes AWS, Google Compute Engine, VMware, OpenStack and Azure.

**Comment by ghost** [comment]
Circle CI 向けに書いた .yaml をローカルで動かす方法は公式で提供されていますが、  
構築前のお試し用という位置づけであるのに加え、  
docker を使うことになるので今回は向いていないかと思います。

https://circleci.com/docs/2.0/local-cli/

**Comment by ghost** [comment]
調査結果: 要件を満たせそうなシステム

* [Appveyor ](https://www.appveyor.com/) プレミアムプラン + GCE/AWS/非公開Dockerサーバ - [参考](https://www.appveyor.com/docs/build-environment/#private-build-cloud)
* 非公開 Jenkins サーバ + テスト結果はPull-reqへのコメント

フロントと task worker を切り離せる CI as a Service は本当に少なかったです。

**Comment by LWisteria** [comment]
> 非公開 Jenkins サーバ + テスト結果はPull-reqへのコメント

こちらにしましょうか（融通がききそうですし）。

この場合、Devloper以外からのPRは自動で実行するとセキュリティ的に厳しいので、Developerの誰かがApproveしたものを実行する、という条件がつくと思います。

**Comment by ghost** [comment]
残りタスク

- [x] ビルド失敗時にログが投稿されることを確認 ……JSONペイロードのエスケープのおはなし
- [x] Collaborator に jenkins-maekawa を追加 (プラグインの都合です)
- [x] Jenkins 設定 と `post_comment.sh` で nsakabe-fixstars/clpy から こちらに向け直す
- [x] Jenkins 設定でこちらのリポジトリのメンテナにビルド承認権限を与える
- [x] Jenkins を専用のUNIXユーザに移し、デーモンとして自動起動するようにする
- [x] fixstars/clpy に PR

**Comment by LWisteria** [comment]
@nsakabe-fixstars vegaとtitanvのどちらかが落ちた時ってどうなりますか？

レビュー失敗にならずに、最後に実行されたどっちかの結果になる気がするんですが、もしそうならあんまりよろしくないので、修正をお願いします。

**Comment by ghost** [comment]
<img width="777" alt="ss 2018-07-11 16 20 57" src="https://user-images.githubusercontent.com/40021205/42578365-a11236da-8526-11e8-971b-02acd9e38854.png">

途中でビルド名を分けたので、どちらかが×だと「1 build failed」みたいな結果になるかと思っています。  
念のため、次回確認します。

**Comment by ghost** [comment]
![default](https://user-images.githubusercontent.com/40021205/42916149-bcc02586-8b3e-11e8-981d-0dd467a8e5ab.PNG)

#20 のとおり、片方おちるとこうなります。

**Comment by ghost** [comment]
別件ですが、 `python setup.py` で走るビルドが失敗したときのエラーメッセージが GitHub コメントに反映されないことに気づきました

**Comment by LWisteria** [comment]
なるほど・・・そしてソレ見て気づいたんですが、そうなると #25 の変更がおかしくなりますね・・・（後に終わったほうが成功するとapproveされてしまう）。

私が勝手にやったやつですが、回避は難しそう。。

**Comment by ghost** [comment]
* approve はユーザごとのステータス
* ビルドの :heavy_check_mark: はビルド名ごとのステータス

なので齟齬が生じますね…

**Comment by LWisteria** [comment]
単に成功した時にはコメントはせずに、自分が成功していてかつ他の @jenkins-maekawa のCI結果が全部OKの時にだけapproveする、とかですかね。。
（失敗した時はrequestで良い

**Comment by ghost** [comment]
もはや shell script でやりたくない領域ですね…。

approval を使いたい理由（CI 結果をみて Developer が反応するのとの違い）としては何がありますか?

**Comment by LWisteria** [comment]
> approval を使いたい理由

単にわかりやすさの問題だけではあります。あと、マージボタンの表示がちょっと変わるので間違えてマージしたりはしづらくなる・・・。

shell scriptじゃなくて他のスクリプト（例えばpython）とかで書き直せば容易だと思います。

**Comment by LWisteria** [comment]
The above problem is handled on #40. I close this issue. Thanks!
