### ISSUE TITLE
Pass clpy_tests/statics_tests/test_correlation.py

### ISSUE THREAD

**Issue by ghost** [fixstars/clpy#103]
We should support, remove, or fix clpy_tests/statics_tests/test_correlation.py
https://github.com/fixstars/clpy/blob/clpy/tests/clpy_tests/statics_tests/test_correlation.py

**Comment by ghost** [comment]
This test has no test case.
So, it was almost solved by #126 
This issue can be closed if add test_correlation.py to ci.

**Comment by LWisteria** [comment]
#134 resolves this issue. Thanks
