### ISSUE TITLE
Pass clpy_tests/math_tests

### ISSUE THREAD

**Issue by ghost** [fixstars/clpy#108]
We should support, remove, or fix clpy_tests/math_tests
https://github.com/fixstars/clpy/blob/clpy/tests/clpy_tests/math_tests

**Comment by ghost** [comment]
test_arithmetic.py
```
E   clpy.backend.ultima.exceptions.UltimaRuntimeError: Return code:1
E   STDERR:
E   /tmp/1211998.798261037.cpp:16:87: error: use of undeclared identifier 'M_PI'
```
 -> https://github.com/fixstars/clpy/pull/131#issue-217921928
* `divide`
* `floor_divide`
* `fmod`
* `power`
* `remainder`

**Comment by ghost** [comment]
test_explog.py
* `exp`
* `exp2`
* `expm1`
* `log`
* `log10`
* `log1p`
* `log2`
* `logaddexp`
* `logaddexp2`

**Comment by vorj** [comment]
After #131 will be merged, we can pass almost test cases by purging unsupported features (half-float and complex) like [this](https://github.com/fixstars/clpy/compare/72-test_fusion_py...vorj:pass-some-tests).

Remained problems are below:

- `test_matmul.py`
    - `test_matmul.py` requires `clpy.backend.memory.MemoryPointer.memset` .
- `test_sumprod.py`
    - `CL_INVALID_GLOBAL_WORK_SIZE` is returned when huge inputs come.
    - For Fixstars developers: **This may break the GPU driver on the primary machine** (and require rebooting), so I strongly suggest to tackle to pass `test_sumprod.py` on the secondary machine.

We should separate this issue to each file.

**Comment by snsato** [comment]
Added math_test that pytest passes by merging https://github.com/fixstars/clpy/pull/131 to test file of jenkins.

**Comment by LWisteria** [comment]
@snsato #158 and #159 make all math_test passed? If not, please leave a comment about which remains

**Comment by snsato** [comment]
There are math_test which do not pass in https://github.com/fixstars/clpy/pull/158 and https://github.com/fixstars/clpy/pull/159.

The remaining tests are as follows

- test_matmul.py
- test_special.py
- test_sumprod.py

**Comment by LWisteria** [comment]
OK. Please keep going!

**Comment by ghost** [comment]
### test_matmul.py
requires `matmul`, which uses sgemmBatched, dgemmBatched routine.
These batched CLBlast routines' api is quite different from cuBLAS's one.

cuBLAS takes **an array of pointers**.
CLBlast takes **a buffer(cl_mem) and offset values to point the beginning of sub-array in the buffer**.

Moreover, CLBlast's offset values are **in elements**, not in bytes.

**Comment by ghost** [comment]
`test_special.py` contains no actual codes.

So the last one is `test_sumprod.py`.
```
test_sumprod.py::TestSumprod::test_sum_axis2_float16 zsh: segmentation fault (core dumped)
```

**Comment by ghost** [comment]
After excluding `half` test,

```
test_sumprod.py::TestSumprod::test_sum_axis_huge FAILED
test_sumprod.py::TestCumprod::test_cumprod_huge_array FAILED 
test_sumprod.py::TestCumprod::test_invalid_axis_lower1 FAILED 
test_sumprod.py::TestCumprod::test_invalid_axis_lower2 FAILED  
test_sumprod.py::TestCumprod::test_invalid_axis_upper1 FAILED    
test_sumprod.py::TestCumprod::test_invalid_axis_upper2 FAILED      
```

**Comment by ghost** [comment]
I'm investigating `test_sumprod.py::TestSumprod::test_sum_axis_huge`'s failure.

`clpy.sum` or `simple_reduction_function`-related something sets wrong `strides`( c_/f_ contiguity)...?

```
numpy.random.seed(0)

shape = (32, 1, 32)
scale = 10
dtype = 'b'

npa = numpy.asarray((numpy.random.rand(*shape) * scale).astype(dtype))
clpya = clpy.asarray((numpy.random.rand(*shape) * scale).astype(dtype))

print(npa.flags.c_contiguous, npa.flags.f_contiguous, npa.strides)
print(clpya.flags.c_contiguous, clpya.flags.f_contiguous, clpya.strides)
print("")

newshape = (32, 32, 32)
npb = numpy.broadcast_to(npa, newshape)
clpyb = clpy.broadcast_to(clpya, newshape)

print(npb.flags.c_contiguous, npb.flags.f_contiguous, npb.strides)
print(clpyb.flags.c_contiguous, clpyb.flags.f_contiguous, clpyb.strides)
print("")

npsum = npb.sum(axis=0)
clpysum = clpyb.sum(axis=0)

print(npsum.flags.c_contiguous, npsum.flags.f_contiguous, npsum.strides)
print(clpysum.flags.c_contiguous, clpysum.flags.f_contiguous, clpysum.strides)
```
```
True False (32, 32, 1)
True False (32, 32, 1)

False False (32, 0, 1)
False False (32, 0, 1)

False True (8, 256)
True False (256, 8)
```

CuPy v2.1.0 shows the same behavior... confusing.

**Comment by ghost** [comment]
#### test_sumprod.py::TestCumprod::test_cumprod_huge_array

on _furyx_
```
    def test_cumprod_huge_array(self):
        size = 2 ** 32
>       a = clpy.ones(size, 'b')

clpy/backend/opencl/api.pyx:211: in clpy.backend.opencl.api.EnqueueNDRangeKernel (clpy/backend/opencl/api.cpp:1434)

E   clpy.backend.opencl.exceptions.OpenCLRuntimeError: CL_INVALID_GLOBAL_WORK_SIZE
```

on _titanv_
```
    def test_cumprod_huge_array(self):
        size = 2 ** 32
        a = clpy.ones(size, 'b')
>       result = clpy.cumprod(a, dtype='b')

clpy/backend/opencl/api.pyx:157: in clpy.backend.opencl.api.BuildProgram

E   clpy.backend.opencl.exceptions.OpenCLRuntimeError: UNKNOWN ERROR: -9999
```

**Comment by ghost** [comment]
on _furyx_, 
`clpy.ones(2**31, 'b')` works well while
`clpy.ones(2**32, 'b')` causes an error.

cf. furyx's Max memory allocation: 1583181004 (1.6GB)

```
>>> clpy.ones(2**32, 'b')
Exception ignored in: 'clpy.backend.opencl.api.CreateBuffer'
Traceback (most recent call last):
  File "clpy/backend/opencl/exceptions.pyx", line 23, in clpy.backend.opencl.exceptions.check_status (clpy/backend/opencl/exceptions.cpp:1599)
clpy.backend.opencl.exceptions.OpenCLRuntimeError: CL_INVALID_BUFFER_SIZE
```

**Comment by ghost** [comment]
As I and @LWisteria discussed verbally, the number of elements (in _huge_ test cases) should be determined by OpenCL memory allocation limit.

**Comment by ghost** [comment]
#199 #205 #206 resolved this issue. congrats!
