### ISSUE TITLE
Pass clpy_tests/random_tests

### ISSUE THREAD

**Issue by ghost** [fixstars/clpy#109]
We should support, remove, or fix clpy_tests/random_tests
https://github.com/fixstars/clpy/blob/clpy/tests/clpy_tests/random_tests

**Comment by ghost** [comment]
Add test for RandomState.uniform due to implemented it at #122 .

**Comment by LWisteria** [comment]
There's test for uniform on [CuPy upstream](https://github.com/cupy/cupy/blob/52a1dc5bd3e98056bd925a707fdfdca2969bd1ea/tests/cupy_tests/random_tests/test_distributions.py), therefore https://github.com/fixstars/clpy/issues/109#issuecomment-422242006 could be resolved by #33 ...?

**Comment by ghost** [comment]
May be it will be resolved.
You mean this issue's task is pass random_tests with out uniform, if we take it before #33 ?

**Comment by LWisteria** [comment]
It was added by https://github.com/cupy/cupy/commit/ac37b21c02ba9a3837a4cb8948e9cd4d7138eb52, therefore we don't need pass test for uniform in this issue before #33.

**Comment by ghost** [comment]
I understood that.

**Comment by ghost** [comment]
I try this issue.

**Comment by ghost** [comment]
- [x] test_distributions.py
- [ ] test_generator.py
 - ` ImportError: cannot import name 'curand'`
- [ ] test_permutations.py
 - ` AttributeError: module 'clpy.random' has no attribute 'shuffle'`
- [ ] test_random.py
 - `AttributeError: module 'clpy.random' has no attribute 'get_random_state'`
- [ ] test_sample.py
 - `AttributeError: module 'clpy.random' has no attribute 'randn'`

**Comment by ghost** [comment]
I suspend to solve this issue.

**Comment by ghost** [comment]
Passed.

https://github.com/fixstars/clpy/blob/e720a936d5dc61e6b8b491e0790269d50c80788b/jenkins/build_and_test.sh#L55
