### ISSUE TITLE
cl_device_type is not consistent

### ISSUE THREAD

**Issue by ghost** [fixstars/clpy#11]
The argument `cl_device_type` on the 2nd time of `GetDeviceIDs`
https://github.com/fixstars/clpy/blob/dec25c342032617d61e6b71ad5836b16005cc29a/clpy/backend/opencl/env.pyx#L37

is not consistent with the 1st time:
https://github.com/fixstars/clpy/blob/dec25c342032617d61e6b71ad5836b16005cc29a/clpy/backend/opencl/env.pyx#L24
(should be a `#define`d constant.)

**Comment by LWisteria** [comment]
@nsakabe-fixstars Thanks for reporting. This is not so critical problem because [current cl.h `#define CL_DEVICE_TYPE_DEFAULT 1`](https://github.com/KhronosGroup/OpenCL-Headers/blob/de26592167b9fdea503885e40e8755393c56523d/CL/cl.h#L265).

However, I agreed with you. This should be fixed.

**Comment by LWisteria** [comment]
af5fc6e6eb0e875a8b71c4aeb1dd4ae6806c048e in #160 unexpectedly fixed this issue.
