### ISSUE TITLE
Pass clpy_tests/prof_tests

### ISSUE THREAD

**Issue by ghost** [fixstars/clpy#110]
We should support, remove, or fix clpy_tests/prof_tests
https://github.com/fixstars/clpy/blob/clpy/tests/clpy_tests/prof_tests

**Comment by ghost** [comment]
This test is testing profiling function.
cupy's profiling function use NVIDIA profiler.
So, I think this test must be removed or skip.

**Comment by LWisteria** [comment]
Yes. this is tests for https://github.com/fixstars/clpy/blob/clpy/clpy/prof/time_range.py . It's difficult to implement compatible one with `NVTX`...

I removed this from target of beta2. Leave this until someone find the solution, library etc.

**Comment by ghost** [comment]
Do I must decorate this test case by pytest's skip and add CI, to close this issue and make new issue like "Add profiling tool" or not?

**Comment by LWisteria** [comment]
This test is decorated with `@unittest.skipUnless(backend.nvtx_enabled`

https://github.com/fixstars/clpy/blob/46b9a6f60b5732bf5167929bf88b75ed5332ebe6/tests/clpy_tests/prof_tests/test_range.py#L9

Therefore, please implement `backend.nvtx_enabled` and return always `False`. then create new issue to support profiler.

**Comment by ghost** [comment]
This issue was solved #191
