### ISSUE TITLE
Pass example_tests

### ISSUE THREAD

**Issue by ghost** [fixstars/clpy#113]
We should support, remove, or fix 
https://github.com/fixstars/clpy/blob/clpy/tests/example_tests

**Comment by ghost** [comment]
- [ ] test_gemm.py
- [x] test_gmm.py
- [x] test_kmeans.py

**Comment by ghost** [comment]
`test_gmm.py`, `test_kmeans.py` have already passed.

### test_gemm.py (error)
performs both **handwritten GEMM kernel** and **internal GEMM (through `clpy.dot(A, B)`)**, comparing each other, in order to show **the usage of user elementwise kernels and how to launch it**.
To make this enabled, we have to rewrite the handwritten one.
(Can be copied from [our prototype](https://github.com/fixstars/clpy/blob/d43b1ec2309ab5a876bf2ce10055ce9f11d38373/clpy/backend/opencl/blas.pyx)? Does it matter?)

**Comment by LWisteria** [comment]
#212 almost resolve this. #216 remains.
