### ISSUE TITLE
Performance report for v2.1.0beta1

### ISSUE THREAD

**Issue by LWisteria** [fixstars/clpy#150]
Update https://github.com/fixstars/clpy/wiki/chainer_example_performance_report

**Comment by LWisteria** [comment]
@snsato you're doing this.

**Comment by snsato** [comment]
## Chainer's Example Execution time(sec)

### v2.1.0b0

| machine       | gpu          | mnist    | ptb         | word2vec  | ImageNet   |
| ------------  | ----------   | -------: | ----------: | --------: | ---------: |
| Primary       | vega         | 107.207  |1153.13 | 496.678  | 693.339    |
| Secondary     | titanv(clpy) |  78.423 | 338.38   | 192.057  | 154.288    |
| Old Primary   | furyx        | 128.069  |  903.01   | 611.510  | 577.687   |
| Old Secondary | gf1060(clpy) |  95.577  |  534.75    |131.491   | 414.213   |
| Secondary     | titanv(cupy) | 39.219 | 156.49     | 28.3194  | 103.452    |
| Old Secondary | gf1060(cupy) | 41.270  |  205.41    |  43.6496   | 106.427    |

### v2.1.0b1

| machine       | gpu          | mnist    | ptb         | word2vec  | ImageNet(googlenetbn)   |ImageNet(nin)   |ImageNet(resnet50)   |
| ------------  | ----------   | -------: | ----------: | --------: | ---------: |---------: |---------: |
| Primary       | vega         | 104.739  |945.09 | 467.335 | 3914.32    | 586.257|4197.82|
| Secondary     | titanv(clpy) | 61.133 |328.05  | 192.122  | 708.352   | 141.106| 678.316|
| Old Primary   | furyx        | 128.240  |  961.88  | 603.988  | 2595.17  |479.688 | 3106.52|
| Old Secondary | gf1060(clpy) |  78.989  | 446.99   |129.846  | 1250.42  |273.049 |1542.72 |
| Secondary     | titanv(cupy) |  |   |  | 225.45  | | 167.53|
| Old Secondary | gf1060(cupy) |   |   |  | 251.64  | | 284.73|

**Comment by snsato** [comment]
@LWisteria 計測結果は上記の通りとなります。

**Comment by LWisteria** [comment]
@snsato ありがとうございます。

* vega,furyxのクロックが変動する問題を調査してもらえますか
* cupyがcudnnを使っていると思いますが、cudnn使わない（cublasのみ）の場合の結果も載せてもらえますか？

**Comment by snsato** [comment]
@LWisteria 承知しました。

**Comment by snsato** [comment]
## Chainer's Example Execution time(sec)

### v2.1.0b0

| machine       | gpu          | mnist    | ptb         | word2vec  | ImageNet   |
| ------------  | ----------   | -------: | ----------: | --------: | ---------: |
| Primary       | vega         | 107.207  |1153.13 | 496.678  | 693.339    |
| Secondary     | titanv(ClPy) |  78.423 | 338.38   | 192.057  | 154.288    |
| Old Primary   | furyx        | 128.069  |  903.01   | 611.510  | 577.687   |
| Old Secondary | gf1060(ClPy) |  95.577  |  534.75    |131.491   | 414.213   |
| Secondary     | titanv(CuPy) | 39.219 | 156.49     | 28.3194  | 103.452    |
| Old Secondary | gf1060(CuPy) | 41.270  |  205.41    |  43.6496   | 106.427    |

### v2.1.0b1

| machine       | gpu          | mnist    | ptb         | word2vec  | ImageNet(googlenetbn)   |ImageNet(nin)   |ImageNet(resnet50)   |
| ------------  | ----------   | -------: | ----------: | --------: | ---------: |---------: |---------: |
| Primary       | vega         | 104.739  |945.09 | 467.335 | 3914.32    | 586.257|4197.82|
| Secondary     | titanv(ClPy) | 61.133 |328.05  | 192.122  | 708.352   | 141.106| 678.316|
| Old Primary   | furyx        | 128.240  |  961.88  | 603.988  | 2595.17  |479.688 | 3106.52|
| Old Secondary | gf1060(ClPy) |  78.989  | 446.99   |129.846  | 1250.42  |273.049 |1542.72 |
| Secondary     | titanv(CuPy) |  |   |  | 225.45  | | 167.53|
| Old Secondary | gf1060(CuPy) |   |   |  | 251.64  | | 284.73|

### CuPy(disable cuDNN)

| machine       | gpu          | mnist    | ptb         | word2vec  | ImageNet(googlenetbn)   |ImageNet(nin)   |ImageNet(resnet50)   |
| ------------  | ----------   | -------: | ----------: | --------: | ---------: |---------: |---------: |
| Secondary     | titanv(CuPy) | 39.067 | 157.97 | 27.846 | 375.465  |115.568 | 278.372|
| Old Secondary | gf1060(CuPy) | 42.370  |205.61 | 43.168 | 544.785  |132.997 | 804.802|

**Comment by snsato** [comment]
@LWisteria CuPyに関してcuDNNを無効化した場合の測定結果を追加しました。

**Comment by LWisteria** [comment]
ありがとうございました。リリース後にwikiに転載します。
