### ISSUE TITLE
test_elementwise.py::test_assign_to_const_qualified_variable is disabled

### ISSUE THREAD

**Issue by LWisteria** [fixstars/clpy#154]
I found #131 removed a test case 0d778ba62e78fb7101b1fc45ad7343e66f490964.

What does this mean and should we enable again?

**Comment by LWisteria** [comment]
@vorj can you answer?

**Comment by vorj** [comment]
@LWisteria 
TL;DR: We can't enable it.

`test_fusion.py` includes some test cases, which overwrites **input** arguments.
So, we needed to disable `const` of input arguments for passing `test_fusion.py` .
That change is [here](https://github.com/fixstars/clpy/pull/131/commits/28ace41baab3c4c896e73dc049dc8ef6db2bf733#diff-330864e5fa6837f1c3838ef858a51a6eL2805).
When we enable `const` and the test case, some test cases on `test_fusion.py` are failed like #177 .

**Comment by LWisteria** [comment]
I misunderstood. The removed test case is not originally from CuPy but added by us. That concludes we do not have to pass the test. Thank you for your investigation!
