### ISSUE TITLE
Performance issue on Random Number Generation

### ISSUE THREAD

**Issue by neko-suki** [fixstars/clpy#162]
I found a problem on random number generation. It affects performance. 

https://github.com/fixstars/clpy/blob/clpy/clpy/random/generator.py#L175

`or self.seed_array.size != numpy.prod(size)`  means when we change the size of randomly generated array, initialization process will run everytime. 

The following is code for measure performance. 

```python
import clpy
import time

def generate_random(size):
    tmp = clpy.random.rand(size)
    

beg = time.time()
generate_random(1) # this case is extremely slow
end = time.time()
print("time = {:.5f} msec".format(end - beg))


beg = time.time()
generate_random(100000)
end = time.time()
print("time = {:.5f} msec".format(end - beg))

beg = time.time()
generate_random(100000)
end = time.time()
print("time = {:.5f} msec".format(end - beg))

beg = time.time()
generate_random( 99999)
end = time.time()
print("time = {:.5f} msec".format(end - beg))

beg = time.time()
generate_random( 99999)
end = time.time()
print("time = {:.5f} msec".format(end - beg))
```

The following is the result of performance measurement on Secondary machine (titanv).  When the size of array to generate random number is changed, it takes long time. 

```
time = 0.12419 msec
time = 0.00214 msec
time = 0.00089 msec
time = 0.00152 msec
time = 0.00023 msec
```

**Comment by LWisteria** [comment]
@neko-suki Did #166 fix this? If so, please close.

**Comment by neko-suki** [comment]
@LWisteria OK. I will close this issue. 

Improved performance is written [here](https://github.com/fixstars/clpy/pull/166#issuecomment-459653468)
