### ISSUE TITLE
linear.py fails with CLBlastInvalidValue exception

### ISSUE THREAD

**Issue by higucheese** [fixstars/clpy#171]
When I run train_mnist.py with ClPy(commit id:001e27da4), I encountered the CLBlastInvalidValue exception in `linear.py`.
The exception did not happen with ClPy(tag:v2.1.0b1).
I investigated which commit causes this problem and found a commit(commit id:af5fc6e6e, "Get all devices") caused the exception.
However, the commit seems not to be associated with arguments of CLBlast;
It just enables to get all lists of devices.
My computing environment has two GPUs(Tesla P100), but I specified only one GPU in an argument of the train_mnist.py

**Comment by LWisteria** [comment]
@higucheese Thanks for reporting. Firstly, I confirmed that train_mnist works on multiple GPU machine on #160. I can not confirmed the error on our [development machine](https://github.com/fixstars/clpy#recommended-system). These are my opinion.

* Development machine is multiple Radeon Vega machine (provided by SAKURA Internet), not NVIDIA's. The cl_platform is different thus there could be some undefined behaiver or runtime bug etc.
* af5fc6e6eb0e875a8b71c4aeb1dd4ae6806c048e changed the device type to get, from `CL_DEVICE_TYPE_DEFAULT` to `CL_DEVICE_TYPE_ALL`. That could cause changing your running device.

**Comment by LWisteria** [comment]
The multi-Vega machine was not lost unexpectedly, thus I checked `python -m clpy train_mnist.py -g0` and no error occurred...

**Comment by LWisteria** [comment]
@higucheese could you give us your executing command and raw output (stdout/stderr) ?

**Comment by LWisteria** [comment]
Anyway, I will try getting multi NVIDIA GPU machine and checking on them.

**Comment by LWisteria** [comment]
[NEWS FLUSH] I got the same error on my GTX1080x2 machine. I'm reporting details soon.

**Comment by LWisteria** [comment]
@higucheese Now I got no error when running `traing_mnist.py` on a machine with multiple NVIDIA GPU. Could you check?

**Comment by higucheese** [comment]
@LWisteria I successfully ran `train_mnist.py` on the machine. Thank you for fixing the bug.
