### ISSUE TITLE
Do not wait for CLBlast

### ISSUE THREAD

**Issue by LWisteria** [fixstars/clpy#174]
Related #153.

#163 removed `clWaitForEvents` on from custom kernel. I found the wating also on [CLBlast](https://github.com/fixstars/clpy/blob/ccd1d34e1fc7ca762489609819aeb9e0c8147942/clpy/backend/opencl/clblast/clblast.pyx#L89). This could/must be removed.

**Comment by vorj** [comment]
#180 fixed this issue, so I close this.
