### ISSUE TITLE
Use importlib for cupy alias

### ISSUE THREAD

**Issue by LWisteria** [fixstars/clpy#18]
Current implementation to `import cupy` alias is forcibly and ill‐mannered.

We should use importlib and replace current.

**Comment by LWisteria** [comment]
@t-kitawaki please take this issue

**Comment by ghost** [comment]
importlib は動的にimportするモジュールを切り替える事が出来る。

例えば、```clpy/cupy/hoge.py```を以下のようにすると、環境変数でcupyを用いた実行とclpyを用いた実行を切り替える事が出来そう（要検証）
```python
import importlib
import os

use_cupy_as_cupy = (os.getenv('USE_CUPY_AS_CUPY') == '1')
if use_cupy_as_cupy:
    # 本物のcupyをimport
    importlib.import_module('cupy_cupy.hoge')
else:
    # clpy をimport
    importlib.import_module('clpy.hoge')
```
この場合本物のcupyとclpy/cupy の名前が衝突するので本物のcupyを別名でinstallしたいが、
pipで簡単に解決することはできず、どこかで行儀の悪い?手法を使うことになる可能性がある。


別の手法としては、importそのものにhookを仕掛けることが出来るらしく、
これを使えば、行儀よく解決できると思われる(要調査)
[https://www.python.org/dev/peps/pep-0302/](url)
のPath hooksを利用する。


importlib の追加に伴い、imp パッケージは廃止予定なのでsetup.py で使われている imp は importlib に移行した方が良さそう

**Comment by ghost** [comment]
分かりやすい日本語解説がありました...
https://pod.hatenablog.com/entry/2017/06/06/013303

**Comment by ghost** [comment]
https://qiita.com/tatuno/items/d2b0732f0bc4e47ed4c6
を参考に実装してみたがうまく動かない
```diff
diff --git a/clpy/__init__.py b/clpy/__init__.py
index 18581c0..ff5b967 100644
--- a/clpy/__init__.py
+++ b/clpy/__init__.py
@@ -1,5 +1,6 @@
 from __future__ import division
 import sys
+import os

 import numpy
 import six
@@ -7,6 +8,10 @@ import six
 from clpy import _version


+from importlib import import_module
+from importlib.abc import MetaPathFinder
+from importlib.machinery import ModuleSpec, SourceFileLoader
+
 try:
     from clpy import core  # NOQA
 except ImportError:
@@ -22,6 +27,32 @@ except ImportError:
     six.reraise(ImportError, ImportError(msg), exc_info[2])


+class CudaAliasMetaPathFinder(MetaPathFinder):
+    def find_spec(fullname, path, target=None):
+        pac_mod = fullname.rsplit('.', maxsplit=1)
+        pac = pac_mod[0]
+        if pac == 'cupy':
+            name = fullname.replace('cupy','clpy')
+            modulename = ''
+            if len(pac_mod)==2:
+                modulename = pac_mod[1]
+            path = os.path.join(os.path.dirname(os.path.abspath(__file__)), modulename.replace('.',os.sep))
+            if os.path.isdir(path):
+                 path = os.path.join(path,'__init__.py')
+            else:
+                 path = path+'.py'
+            print(path)
+            return ModuleSpec(
+                name=name,
+                loader=SourceFileLoader(name, path),
+                origin=path,
+           )
+
+
+if sys.meta_path[0].__name__ != 'CudaAliasMetaPathFinder':
+    sys.meta_path.insert(0, CudaAliasMetaPathFinder)
+
+
 from clpy import backend
```

**Comment by ghost** [comment]
sys.meta_path に cupy 以下のパッケージの場合だけclpyにrenameしたModuleSpecを返すMetaPathFinderを追加すると動くと思われる…

**Comment by ghost** [comment]
clpy にrename するのではなく、今の clpy/cupy を(別名にして？)叩きに行くべき。
find_spec内でpathの複雑な読み替えはしないほうが良い。

**Comment by ghost** [comment]
hookを仕掛けることには成功したが、 ```No module named 'cupyx'```とエラーが出る 69255d5ebb0e1d43991e621439306157450b9a2a

**Comment by ghost** [comment]
```No module named 'cupyx'```のエラーはchainerのversion選択ミスでした…

**Comment by ghost** [comment]
package の場合もfileをSourceFileLoaderを指定したら動くようになった a48a24733b7f1d7470389438b2cbc048db409dc9

**Comment by ghost** [comment]
cupyと共存できるように、cupyのalias名をcupy_aliasに変更するようにした。
また、import clpyをしていても、環境変数```CLPY_NOT_HOOK_CUPY=1```の場合hookを仕掛けないようにした。
 240b72093309949afb87bde1dfb0ef1a80555353

**Comment by ghost** [comment]
python の実行時オプションにモジュールの初期化時にメッセージを出す `-v` がある。
これをつけておくとモジュールのimport時にどのソースを読んだかを出力してくれる。
https://docs.python.org/ja/3.5/using/cmdline.html#id4

**Comment by LWisteria** [comment]
Resolved by #20, thank you
