### ISSUE TITLE
CLPY_TEST_GPU_LIMIT must be removed

### ISSUE THREAD

**Issue by vorj** [fixstars/clpy#182]
#136 says that [this line](https://github.com/fixstars/clpy/blob/18fa78f1f297681d2ce01f693743a692a963fe93/jenkins/build_and_test.sh#L95) must be removed when #4 is closed, but the line is still alive.

Note: When `CLPY_TEST_GPU_LIMIT` is not defined, some tests raise SEGV.

**Comment by LWisteria** [comment]
OK. I'm checking.

**Comment by LWisteria** [comment]
I think #136 is wrong. Accoring to [CuPy document](https://docs-cupy.chainer.org/en/v2.1.0.1/contribution.html), `CUPY_TEST_GPU_LIMIT` must be the same number of GPU on the machine. So we can't remove it on our machine.

@t-kitawaki How do you think?

**Comment by LWisteria** [comment]
[What the code says](https://github.com/fixstars/clpy/blob/c5f2aaa1fc8c8334161532f7f36ed8e3e91da6b3/clpy/testing/attr.py#L54-L56) is the same as that document. There are no limitation of number of GPUs to run if the machine has less GPUs. [Latest CuPy](https://github.com/cupy/cupy/blob/7ba218bfc1360672e94ef7a13d0e3993fc425989/cupy/testing/attr.py) also has no limitation.

**Comment by LWisteria** [comment]
The test result on https://github.com/fixstars/clpy/pull/187#issuecomment-464948697 

> However, I can't reproduce it...

was on the multi-GPU machine. Therefore, I confirmed the test without CUPY_TEST_GPU_LIMIT was passed.

**Comment by ghost** [comment]
@LWisteria You mean 

> `export CLPY_TEST_GPU_LIMIT=1` must be removed when multiple device support is implemented(#4).

is wrong?
I think you are right.

I had assumption to CI machine will be multi gpu macine when multi gpu was supported. 
Sorry for wrong message.

**Comment by LWisteria** [comment]
@t-kitawaki OK. Thanks.

I conclude this PR is wrong and `CLPY_TEST_GPU_LIMIT` must **not** be removed.

@vorj could you close with `invalid` label?

**Comment by vorj** [comment]
@LWisteria @t-kitawaki Thank you for your investigation. I close it.
