### ISSUE TITLE
OpenCL version check

### ISSUE THREAD

**Issue by LWisteria** [fixstars/clpy#2]
We must check system OpenCL (platform, device, OpenCL C) version when installing and/or execution.

**Comment by ghost** [comment]
(OpenCL C Version に関しては) `headercvt` の出力する `preprocessor_defines.pxi` に
```
cdef extern from "CL/cl.h":
    cdef enum:
        ...
        CL_VERSION_1_0
        CL_VERSION_1_1
        CL_VERSION_1_2
```

があるからこれを見れば良い?

**Comment by ghost** [comment]
* Platform version
* Device version
* Device OpenCL C version

のどれを(あるいは全部)チェックするかどうか。

**Comment by ghost** [comment]
@nsakabe-fixstars お願いします！

**Comment by ghost** [comment]
ビルド時にいの一番にバージョンチェックを走らせて

* OpenCL C >= 1.2
* Platform(#0) Version >= 1.2

を保証することができました(右辺は簡単に変更可能)。

同じプログラムで、実行時に

* Device(#n) Version >= 1.2

を確認することができるので、これから `env.pyx` に組み込もうと思いますが、マルチデバイスの対応方針が決まるまでは真面目に作り込まないほうがよさそうです。

**Comment by ghost** [comment]
Closing this issue since #132 has been merged.
