### ISSUE TITLE
Port examples/gemm

### ISSUE THREAD

**Issue by LWisteria** [fixstars/clpy#216]
As https://github.com/fixstars/clpy/issues/113#issuecomment-476505608 reports, [examples/gemm](https://github.com/fixstars/clpy/tree/clpy/examples/gemm) is an example to show how to compile and run raw kernel codes.
That is not problem depends only on ClPy's lack of functions. Therefore it is not passed in v2.1.0rc1.

However, it's not difficult to rewrite into OpenCL and ClPy.

**Comment by LWisteria** [comment]
@shusukeueda よろしくお願いします

**Comment by shusukeueda** [comment]
こちら着手します

**Comment by shusukeueda** [comment]
現状 `python sgemm.py` すると `clpy.backend.compile_with_cache` がないので動かない。`cupy.cuda.compile_with_cache` はある

**Comment by ghost** [comment]
CUDA C++ → OpenCL C 変換（ [_ultima_](https://github.com/fixstars/clpy/blob/clpy/ultima/ultima.cpp) ） が入っているので、 cupy とずいぶん変わっているところです。

compile_with_cache は以下にあって、 core/core.pyx にインクルードされています
https://github.com/fixstars/clpy/blob/016015aea2367dad02a631d7d87e1f45f9d9efc9/clpy/core/carray.pxi#L147

**Comment by vorj** [comment]
なんで今は `clpy.core.core.compile_with_cache` ですね

**Comment by LWisteria** [comment]
これ、なんで元からcore.coreじゃなくて.cudaにあるんでしたっけ？移動した覚えはないので、`clpy.backend`あたりで、なんかのexportか何かを忘れているだけ？

**Comment by LWisteria** [comment]
あーこれ、本来は[cupy.cuda.compiler](https://github.com/cupy/cupy/blob/v2.1.0/cupy/cuda/compiler.py#L108)にあったのを、clpyにした時にcompilerからcoreに無理やり持ってきたんですね・・・。
正しい形としては、clpy.backend.compilerとかを置くべきか・・・？

**Comment by vorj** [comment]
まぁ少なくとも `carray` ではないよなぁと思い(ながら作業して)ましたね

**Comment by shusukeueda** [comment]
ひとまず `clpy.core.core.compile_with_cache` を使うように変更しました。
ちなみに `clpy.backend` で `compiler` と `compiler.compile_with_cache` のインポートがコメントアウトされていました
https://github.com/fixstars/clpy/blob/016015aea2367dad02a631d7d87e1f45f9d9efc9/clpy/backend/__init__.py#L54

**Comment by LWisteria** [comment]
あー、正しくは、[元からcarrayからcuda(.compiler)を呼び出していた](https://github.com/cupy/cupy/blob/v2.1.0/cupy/core/carray.pxi#L149)のを、compilerを使わなくなったので無いんですね。

**Comment by LWisteria** [comment]
と、いうことは、今のcarrayがcuda.compilerが元からやっていた機能も混じって実装してしまっているのが問題なので、たぶん[ビルドしている辺り](https://github.com/fixstars/clpy/blob/016015aea2367dad02a631d7d87e1f45f9d9efc9/clpy/core/carray.pxi#L191-L200)を、backend.compilerに移動する（戻す？）のが正しい実装な気がしますね。

@nsakabe-fixstars @vorj どう思います？

**Comment by vorj** [comment]
理解しました、対応を取るなら `cuda.compile_with_cache` 相当を生やすべきでしょうね(ClPyだと `cdef` になる？)

**Comment by LWisteria** [comment]
@shusukeueda ということで、とりあえずcore.coreでもいいですが、最終的にはそのようにしてください。

**Comment by shusukeueda** [comment]
処理の流れ (メモ)
- `utils.read_code` で `sgemm.cu` を読み込んで定数を `#define` (ここは通る)
- `utils.load_kernel` でコンパイル、`core.core.compile_with_cache` から ultima を呼んでいるがエラー

**Comment by shusukeueda** [comment]
とりあえずエラーが出ているところ

`sgemm.cu` のコンパイル
- `threadIdx`、`__syncthreads()` がないので ultima がエラー
- 配列の添字が整数でない
```
/tmp/105265.872887878.cpp:93:38: error: array subscript is not an integer
            sA[n + idyA][m + idxA] = fetch(offs_dA, M, m, n, boundA);
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/105265.872887878.cpp:38:41: note: expanded from macro 'fetch'
#define fetch(arr, col, m, n, bound) arr[min(n*col + m, bound)]
```
整数に見えるが... 検証中
- `extern "C"` のところで `expected identifier or '('` が出る (?)

とりあえず手動で直すとコンパイルは通って次に進めるが
- カーネル実行のところで `shared_mem` は引数にない (`local_mem` っぽい)
- `CL_INVALID_KERNEL`

**Comment by LWisteria** [comment]
まぁCUDAカーネルを渡してOpenCLがコンパイル＆実行できるわけはないので・・・（そこをちゃんとOpenCL Cに書き換える、というのがこのissueの本題です）

**Comment by shusukeueda** [comment]
確認ですが、`sgemm.cu` を OpenCL カーネル `.cl` に書き換える (+ `compile_with_cache` が `core.core` にあるのを正しい位置に移す) のが目的ということで合っていますか？

**Comment by LWisteria** [comment]
目的は「examples/gemmをClPyで動かすこと」なので、手段はそれに合わせて選んでください

**Comment by shusukeueda** [comment]
(メモ) とりあえず `sgemm.cu` をエラー箇所について機械的に OpenCL カーネルに書き直して、いま `SetKernelArg` がエラー出ているのでカーネル引数を適切に設定する必要がありそう

**Comment by shusukeueda** [comment]
`SetKernelArg` が失敗するので単純なカーネルで試してみようと思い、
ベクトルの足し算 [test.py](https://github.com/fixstars/clpy/blob/216-gemm/examples/gemm/test.py) と [test.cl](https://github.com/fixstars/clpy/blob/216-gemm/examples/gemm/test.cl) を作ってみましたが `CL_INVALID_ARG_SIZE` が出ます。
メモリバッファを 3 つ確保するだけなはずなのですが、なにか間違ってるでしょうか。
(`python test.py` で実行できます)

**Comment by LWisteria** [comment]
@shusukeueda WIP(draft)でPRを投げてください

**Comment by shusukeueda** [comment]
PR #243 を作りました。

**Comment by shusukeueda** [comment]
カーネルに 2 次元配列を渡すと怒られるので 1 次元配列に変換して渡すようにします。
あと縦横のサイズなど定数を渡す必要がありますが同じ `CL_INVALID_ARG_SIZE` が出るので検証中

**Comment by vorj** [comment]
`CArray_2` でも怒られますか？

**Comment by shusukeueda** [comment]
そもそも `kernel parameter cannot be declared as a pointer to a pointer` と言われていて 2 次元配列が宣言できません...
いろいろ見てみてもだいたい 1 次元配列に直して計算しているので、そういう仕様なのかと思いましたが、何かいい方法がありますか？

**Comment by shusukeueda** [comment]
全部 1 次元配列にすれば動くことには動きますが、定数と 2 次元配列が使えないの悲しいので PR で質問させていただきます...

**Comment by shusukeueda** [comment]
PR #244 でお願いします。

**Comment by shusukeueda** [comment]
とりあえず動くようにはなりました。結果が `cp.dot` と合わないので修正していきます

**Comment by shusukeueda** [comment]
CUDA カーネルで `__shared__` になっているところをローカルメモリにしたい。
[`clpy.core.core.LocalMem` のインスタンスを渡すと `local_mem` で指定したサイズのローカルメモリを確保](https://github.com/fixstars/clpy/blob/016015aea2367dad02a631d7d87e1f45f9d9efc9/clpy/backend/function.pyx#L76)

**Comment by shusukeueda** [comment]
m, n, k が数百くらいだと `sgemm(A, B)` と `cp.dot(A, B)` が一致するが小さかったり (<10) 大きかったり (>1000) すると落ちる (謎)
小さいのはワークグループ 1 個だけみたいなときに変になるのかもしれない。
大きいのは謎 ~~(なんか `cp.random.uniform` が変になっていそう)~~ `print` の問題っぽい

**Comment by shusukeueda** [comment]
とりあえずカーネルは正しく動いていそうなのでサイズが大きいときはおいておくことにして (+ 小さいときは CUDA カーネルがもともと対応していない)、先に進みます

**Comment by shusukeueda** [comment]
ベンチマークのところはいまのところ実装されていないので、とりあえず飛ばす

**Comment by LWisteria** [comment]
#246 が通ったので、これで https://github.com/fixstars/clpy/tree/clpy/tests/example_tests が全部通せることになりますね！

@shusukeueda https://github.com/fixstars/clpy/blob/clpy/jenkins/build_and_test.sh に追加してCIに組み込んでもらえますか

**Comment by shusukeueda** [comment]
テストを追加しました (#247)。
ベンチマークの部分をできるようにするため、まず CUDA / OpenCL の Event の使い方を確認していきます

**Comment by shusukeueda** [comment]
CuPy の `Event` クラスは [`cuda/stream.pyx`](https://github.com/fixstars/clpy/blob/clpy/clpy/backend/cuda/stream.py) で定義、
[`cuda/runtime.pyx`](https://github.com/fixstars/clpy/blob/clpy/clpy/backend/cuda/runtime.pyx) でラップした CUDA の runtime API を呼んでいる
`record` メソッド (`cudaEventRecord`) でカーネルの前後にイベントを登録、
`synchronize` (`cudaEventSynchronize`) で同期、
`get_elapsed_time` 関数 (`cudaEventElapsedTime`) で時刻の差を計算

現状 ClPy の `runtime.pyx` がないので、そのあたりを書く必要がある？
OpenCL で時刻を返してくれる API は [`clGetEventProfilingInfo`](https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/clGetEventProfilingInfo.html) あたりでしょうか。

**Comment by LWisteria** [comment]
runtimeに相当するところはapiとかにあります（名前を揃えたほうが良かったですねそういえば）。

OpenCLだとそれで合ってますが、使い方は割と違うかもしれないので、どうやって吸収するかがその主題だと思います。

**Comment by shusukeueda** [comment]
`api` で定義されていました

正確かわかりませんが、CUDA のイベントはタスク (カーネル実行) の間にあってそこを通過した時刻を記録する感じなのに対して、OpenCL のイベントはタスクに紐付けられてそのタスクが開始/完了した時刻を記録していそう

なので、いま start イベント → sgemm or cp.dot 実行 → end イベントとして start と end の差を計算していますが、  
sgemm の中でも複数回 OpenCL API を叩いている (はず) なのと、~~そもそも cp.dot は OpenCL じゃない~~ (cuBLAS / CLBlast 呼んでるのか) ので、どうイベントを配置するかが問題

とりあえず vector add あたりのコードで `clGetEventProfilingInfo` を試してみています。

**Comment by shusukeueda** [comment]
`clCreateCommandQueue` で `CL_QUEUE_PROFILING_ENABLE` しないとバグる

**Comment by shusukeueda** [comment]
CuPy では `sgemm` あるいは `cp.dot` 全体にかかる時間を測定している
(カーネルのコンパイルなども含む) ので、ClPy でも処理の最初と最後にダミーのタスクを立てて、それに紐付けたイベントを使って実行時間を計算することを考えました

`clCreateCommandQueue` の引数は [このあたり](https://github.com/fixstars/clpy/blob/8fbb365457c3615bbbe67c73c78268ce5fa0b11c/clpy/backend/opencl/env.pyx#L135)？

**Comment by shusukeueda** [comment]
そもそも最初と最後で測るのなら Python の `time` とかでもいいのでは？ と思いましたが精度が悪いのでだいぶゆらぐ

titanv で CuPy ですが、
```
m=1440 n=1492 k=654
start benchmarking

=============================Result===============================
hand written kernel time           1.4694547247886658 ms
hand written kernel time in Python 1.3856061299641926 ms
cuBLAS time                        0.6741302412748337 ms
cuBLAS time in Python              0.6902448336283366 ms
```

`in Python` が `time` で計った時間 (100 回平均 = 0.1 秒くらいなので、`time` の誤差で死んでいる`

**Comment by shusukeueda** [comment]
とりあえず vega でベンチマークは動くようになったが結果が変
(titanv ではだいたい合っているので `time.time` の誤差ではなさそう)

`Event` クラスは後でちゃんとした場所に移す

**Comment by shusukeueda** [comment]
前後にダミーのカーネル (引数なし、何もしない) を立ててそれに紐付けたイベントで時刻を計測したら `time` で計った時間よりだいぶ長くなる
```
m=705 n=598 k=1414
start benchmarking

=============================Result===============================
hand written kernel time          : 1.496375 ms
hand written kernel time in Python: 0.287446 ms
cuBLAS time                       : 1.031488 ms
cuBLAS time in Python             : 0.056488 ms
```

コンパイルがキャッシュできてないか、あるいは同期がうまくできていないのかも。
ちなみに、`time.time` より `time.perf_counter` の方が精度がいいらしい

**Comment by shusukeueda** [comment]
コンパイルのキャッシュはできている。
キャッシュしても 0.1 msec くらいかかっていて無視はできないが、 ~~sgemm も cp.dot も同様にかかるはずなので差が出ているのはこれのせいではないはず~~ 勘違い

Python の time で測るときに 1 回ずつブロックしないといけない気がする
`cudaEventSynchronize` の代わりに `clFinish` とかをうまく使うとできるかも
と思ったが、titanv では cudaEvent と time で合っているので...

**Comment by shusukeueda** [comment]
Python の time で sgemm/cp.dot 複数回の合計時間を図っていたのを毎回 `clFinish` を挟むようにしたら `clGetEventProfiling` で測った時間と近くなったので、これでいい気がする
```
m=300 n=300 k=450
start benchmarking

Checked sgemm(A, B) = cp.dot(A, B).
=============================Result===============================
hand written kernel time          : 0.516072 ms
hand written kernel time in Python: 0.501633 ms
cuBLAS time                       : 0.220765 ms
cuBLAS time in Python             : 0.214195 ms
```

**Comment by shusukeueda** [comment]
Cython 周りでおかしくなったら cdef / cpdef、import + cimport が合っているか確認

**Comment by shusukeueda** [comment]
`Event` オブジェクトを `clpy.backend` に移したら遅くなった...
(ダミーカーネルのコンパイルのキャッシュが効かなくなっている)

**Comment by shusukeueda** [comment]
一回の計測の間ではキャッシュ効いているので測定には問題なさそうだった。
別の要因で 0.2-0.4 msec くらい遅くなっている

**Comment by LWisteria** [comment]
とりあえず機能的に成立していることと、速度が遅いことの問題は分けたほうが良いかと思います（後者は無限に沼になって #153 に行き着いてしまう可能性があるので）

機能が使えているところまでを一旦まとめてPRにしませんか？

**Comment by shusukeueda** [comment]
あ、CuPy より遅いっぽいのはそうなんですが、
`time.perf_counter` で測ったときより `Event` オブジェクトで測ったときの方が遅くなることがあって謎になっていました

> Python の time で sgemm/cp.dot 複数回の合計時間を図っていたのを毎回 `clFinish` を挟むようにした

段階では等しくなっていたので、クラスの定義の場所を変えたのがよくないのかもしれないです
が、とりあえず動いてはいるので、いったん PR にします

**Comment by shusukeueda** [comment]
あ、[`clEnqueueBarrierWithWaitList`](https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clEnqueueBarrierWithWaitList.html) とか使った方が楽なのでは...

**Comment by shusukeueda** [comment]
`clEnqueueWithBarrierWithWaitList` を使うようにしたら `time` の結果と一致したので、これでよさそう

**Comment by shusukeueda** [comment]
`CL_` の定数、`opencl/preprocessor_defines.pxi` で定義されているので普通に使える (なんで使えないと思ったのか)

**Comment by LWisteria** [comment]
@shusukeueda primary/secondaryでのcupy/clpyでの計測結果を貼ってください（それで完了ですかね）。

**Comment by shusukeueda** [comment]
m = n = k = 500 で計測 (大きくすると vega で変になるのが解消されていないので...)
けっこうゆらぎますが、

vega、ClPy
SGEMM 0.68 msec / clpy.dot 0.38 msec

titanv、CuPy
SGEMM 0.55 msec / cupy.dot 0.25 msec

となりました (± 20 μsec くらい)

**Comment by LWisteria** [comment]
titanvのClPyはどんなぐらいですか？

**Comment by shusukeueda** [comment]
なんか titanv の ClPy、`clGetEventProfilingInfo` が結果返してくれなくて 0 が表示されているので確認中です...

**Comment by shusukeueda** [comment]
結果自体は `time` で測ったのとあまり変わらないはずなので、それで測ると
m = n = k = 500
titanv、ClPy
SGEMM 0.74 msec / clpy.dot 0.29 msec
(± 20 μsec くらいゆらぐ) くらいな感じです

**Comment by shusukeueda** [comment]
titanv の ClPy を入れ直してみましたが 0 が表示される...
`clGetEventProfilingInfo` 自体は呼ばれているので、？

**Comment by LWisteria** [comment]
> clGetEventProfilingInfo が結果返してくれな

はそれはそれで問題なので、調査と（可能であれば）修正をお願いします・・・。

**Comment by shusukeueda** [comment]
titanv、適当に C でホストとカーネルを書いて生の OpenCL で動かすと `clGetEventProfiling` はできる (正しそうな結果が返る)。
`sgemm.py` のときに `clGetEventProfiling` は動いているが結果が 0 になる

ClPy の入れ方が悪いかもしれないので、確認してみます

**Comment by LWisteria** [comment]
> 適当に C でホストとカーネルを書いて生の OpenCL で動かすと clGetEventProfiling はできる (正しそうな結果が返る)。

一応その試験コードを貼ってもらえますか？

**Comment by shusukeueda** [comment]
ホスト

```c
// OpenCL でベクトルの足し算
// vec1 と vec2 を足して vec3 に代入

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <CL/cl.h>

#define MAX_SOURCE_SIZE (0x100000)

int main(const int argc, const char** argv) {

    // 引数チェック
    if (argc != 2) {
        fprintf(stderr, "Usage: %s <global_data_size>\n", argv[0]);
        exit(1);
    }
 
    // データの初期化
    const size_t global_data_size = atoi(argv[1]);
    const size_t memsize = global_data_size * sizeof(double);

    double* vec1 = (double*)malloc(memsize);
    double* vec2 = (double*)malloc(memsize);
    double* vec3 = (double*)malloc(memsize);
    if (!vec1 || !vec2 || !vec3) {
        free(vec1);
        free(vec2);
        free(vec3);
        perror("malloc failed");
        exit(1);
    }
    for (int i = 0; i < global_data_size; i++) {
        vec1[i] = (double)i;
        vec2[i] = (double)i;
    }
     
    cl_int ret;
    bool any_has_failed = false;
    char* fail_message;

    // プラットフォームの特定
    cl_platform_id platform_id = NULL;
    cl_uint ret_num_platforms;
    if (!any_has_failed) {
        ret = clGetPlatformIDs(1, &platform_id, &ret_num_platforms);
        if (ret != CL_SUCCESS) {
            fail_message = "clGetPlatformIDs failed\n";
            any_has_failed = true;
        } else if (ret_num_platforms != 1) {
            fail_message = "The number of the obtained platforms is not 1\n";
            any_has_failed = true;
        }
    }

    // デバイスの特定
    cl_device_id device_id = NULL;
    cl_uint ret_num_devices;
    if (!any_has_failed) {
        ret = clGetDeviceIDs(platform_id, CL_DEVICE_TYPE_DEFAULT, 1, &device_id, &ret_num_devices);
        if (ret != CL_SUCCESS) {
            fail_message = "clGetDeviceIDs failed\n";
            any_has_failed = true;
        } else if (ret_num_devices != 1) {
            fail_message = "The number of the obtained devices is not 1\n";
            any_has_failed = true;
        }
    }

    // コンテキストの作成
    cl_context context = NULL;
    if (!any_has_failed) {
        context = clCreateContext(NULL, 1, &device_id, NULL, NULL, &ret);
        if (ret != CL_SUCCESS) {
            fail_message = "clCreateContext failed\n";
            any_has_failed = true;
        }
    }

    // コマンドキューの作成
    cl_command_queue command_queue = NULL;
    if (!any_has_failed) {
        command_queue = clCreateCommandQueue(context, device_id, CL_QUEUE_PROFILING_ENABLE, &ret);
        if (ret != CL_SUCCESS) {
            fail_message = "clCreateCommandQueue failed\n";
            any_has_failed = true;
        }
    }

    // メモリオブジェクトの作成
    cl_mem memobj_vec1 = NULL, memobj_vec2 = NULL, memobj_vec3 = NULL;
    cl_int ret_vec1, ret_vec2, ret_vec3;
    if (!any_has_failed) {
        memobj_vec1 = clCreateBuffer(context, CL_MEM_READ_ONLY, memsize, NULL, &ret_vec1);
        memobj_vec2 = clCreateBuffer(context, CL_MEM_READ_ONLY, memsize, NULL, &ret_vec2);
        memobj_vec3 = clCreateBuffer(context, CL_MEM_WRITE_ONLY, memsize, NULL, &ret_vec3);
        if (ret_vec1 != CL_SUCCESS || ret_vec2 != CL_SUCCESS || ret_vec3 != CL_SUCCESS) {
            fail_message = "clCreateBuffer failed\n";
            any_has_failed = true;
        }
    }

    // メモリバッファにデータを転送
    if (!any_has_failed) {
        ret_vec1 = clEnqueueWriteBuffer(command_queue, memobj_vec1, CL_TRUE, 0, memsize, vec1, 0, NULL, NULL);
        ret_vec2 = clEnqueueWriteBuffer(command_queue, memobj_vec2, CL_TRUE, 0, memsize, vec2, 0, NULL, NULL);
        if (ret_vec1 != CL_SUCCESS || ret_vec2 != CL_SUCCESS) {
            fail_message = "clEnqueueWriteBuffer failed\n";
            any_has_failed = true;
        }
    }

    // カーネルファイルの読み込み
    const char* filename = "vector_add_kernel.cl";
    FILE* f;
    if (!any_has_failed) {
        f = fopen(filename, "r");
        if (!f) {
            fail_message = "Failed to load kernel\n";
            any_has_failed = true;
        }
    }

    char* source_str;
    if (!any_has_failed) {
        source_str = (char*)malloc(MAX_SOURCE_SIZE);
        if (!source_str) {
            fail_message = "Failed to malloc source_str\n";       
            any_has_failed = true;
        } 
    }
    
    size_t source_size;
    if (!any_has_failed) {
        source_size = fread(source_str, sizeof(char), MAX_SOURCE_SIZE, f);
        if (source_size == 0) {
            fail_message = "Empty kernel source code\n";
            any_has_failed = true;
        }
    }
    
    if (f) {
        fclose(f);
    }

    // プログラムオブジェクトの作成
    cl_program program = NULL;
    if (!any_has_failed) {
        program = clCreateProgramWithSource(context, 1, (const char**)&source_str, (const size_t*)&source_size, &ret);
        if (ret != CL_SUCCESS) {
            fail_message = "clCreateProgramWithSource failed\n";
            any_has_failed = true;
        }
    }

    // ビルド
    if (!any_has_failed) {
        ret = clBuildProgram(program, 1, &device_id, NULL, NULL, NULL);
        if (ret != CL_SUCCESS) {
            fail_message = "clBuildProgram failed\n";
            any_has_failed = true;
        }
    }

    // カーネルオブジェクトの作成
    cl_kernel kernel = NULL;
    if (!any_has_failed) {
        kernel = clCreateKernel(program, "vector_add", &ret);
        if (ret != CL_SUCCESS) {
            fail_message = "clCreateKernel failed\n";
            any_has_failed = true;
        }
    }

    // カーネル引数の設定
    if (!any_has_failed) {
        ret_vec1 = clSetKernelArg(kernel, 0, sizeof(cl_mem), &memobj_vec1);
        ret_vec2 = clSetKernelArg(kernel, 1, sizeof(cl_mem), &memobj_vec2);
        ret_vec3 = clSetKernelArg(kernel, 2, sizeof(cl_mem), &memobj_vec3);
        if (ret_vec1 != CL_SUCCESS || ret_vec2 != CL_SUCCESS || ret_vec3 != CL_SUCCESS) {
            fail_message = "clSetKernelArg failed\n";
            any_has_failed = true;
        }
    }

    // カーネルの実行
    cl_event event;
    if (!any_has_failed) {
        ret = clEnqueueNDRangeKernel(command_queue, kernel, 1, NULL, &global_data_size, NULL, 0, NULL, &event);
        if (ret != CL_SUCCESS) {
            fail_message = "clEnqueueTask failed\n";
            any_has_failed = true;
        }
    }
    clWaitForEvents(1, &event);
    size_t start, end;
    clGetEventProfilingInfo(event, CL_PROFILING_COMMAND_START, sizeof(start), &start, NULL);
    printf("start: %lu\n", start / 1000);
    clGetEventProfilingInfo(event, CL_PROFILING_COMMAND_END, sizeof(end), &end, NULL);
    printf("end: %lu\n", end / 1000);
    printf("elapsed: %lu\n", (end - start) / 1000); // microseconds

    // メモリオブジェクトからの読み込み
    if (!any_has_failed) {
        ret = clEnqueueReadBuffer(command_queue, memobj_vec3, CL_TRUE, 0, memsize, vec3, 0, NULL, NULL);
        if (ret != CL_SUCCESS) {
            fail_message = "clEnqueueReadBuffer failed\n";
            any_has_failed = true;
        }
    }
 
    // オブジェクト解放
    ret = clReleaseKernel(kernel);
    ret = clReleaseProgram(program);
    ret = clReleaseMemObject(memobj_vec1);
    ret = clReleaseMemObject(memobj_vec2);
    ret = clReleaseMemObject(memobj_vec3);
    ret = clReleaseCommandQueue(command_queue);
    ret = clReleaseContext(context);

    free(vec1);
    free(vec2);
    free(vec3);
 
    return 0;
}
```

カーネル
```c
__kernel void vector_add(__global const double* vec1, __global const double* vec2, __global double* res) {
    const int i = get_global_id(0);
    res[i] = vec1[i] + vec2[i];
}
```

で、`gcc -I/usr/local/cuda/include vector_add.c -o vector_add -lOpenCL` → `./vector_add 100000` すると 10 μsec くらいというそれっぽい結果が出ます

**Comment by LWisteria** [comment]
`clEnqueueBarrierWithWaitList`だと動かない、ということではないですか？

**Comment by shusukeueda** [comment]
カーネル実行以外のところは上のコードと同じで、
A:
```c
cl_event event;
clEnqueueNDRangeKernel(command_queue, kernel, 1, NULL, &global_data_size, NULL, 0, NULL, &event);
clWaitForEvents(1, &event);
size_t time;
clGetEventProfilingInfo(event, CL_PROFILING_COMMAND_END, sizeof(time), &time, NULL);
printf("Kernel time: %lu usec\n", time / 1000);
```
と B:
```c
cl_event event;
clEnqueueNDRangeKernel(command_queue, kernel, 1, NULL, &global_data_size, NULL, 0, NULL, NULL);
clEnqueueBarrierWithWaitList(command_queue, 0, NULL, &event);
clWaitForEvents(1, &event);
size_t time;
clGetEventProfilingInfo(event, CL_PROFILING_COMMAND_END, sizeof(time), &time, NULL);
printf("Barrier time: %lu usec\n", time / 1000);
```
をやったときに、vega だと両方適当な時刻が出ていて、titanv だと A は適当な時刻がでるのに B は 0 が返ります (なぜ)

**Comment by LWisteria** [comment]
`clEnqueueBarrierWithWaitList`は「そこで待つ」なので、Barrierを入れる前にとっくにKernelは終わっている、とかでは？

**Comment by shusukeueda** [comment]
すでにカーネルが終わっている可能性はありますが、デバイスタイムカウンタを返すはずなので何らかの時刻が出てほしい気持ちがあります...

**Comment by LWisteria** [comment]
clGetEventProfilingInfoはなにかエラーを出しているわけではないですか？（エラー処理していないように見えますが）

**Comment by shusukeueda** [comment]
問題の titanv + `clEnqueueBarrierWithWaitList` の場合にはエラーは出ていないです。

ただ、結果の時刻が 0 になるパターンはあって、
vega などで `clGetEventProfilingInfo` までにコマンドが終わっていないと `CL_PROFILING_INFO_NOT_AVAILABLE` (-7) を吐いて時刻 0 を返すようです

```c
cl_event event;
clEnqueueNDRangeKernel(command_queue, kernel, 1, NULL, &global_data_size, NULL, 0, NULL, NULL);
ret = clEnqueueBarrierWithWaitList(command_queue, 0, NULL, &event);
printf("Return: %d\n", ret);
// clWaitForEvents(1, &event);
size_t time = 777;
ret = clGetEventProfilingInfo(event, CL_PROFILING_COMMAND_END, sizeof(time), &time, NULL);
printf("Return: %d\n", ret);
printf("Barrier time: %lu usec\n", time / 1000);
```
すると
@ titanv
```
Return: 0
Return: 0
Barrier time: 0 usec
```

@ vega
```
Return: 0
Return: -7
Barrier time: 0 usec
```

**Comment by LWisteria** [comment]
ふと思ったんですが、`clEnqueueMarker`だったらうまく行ったりしませんか？

**Comment by shusukeueda** [comment]
```c
cl_event event;
clEnqueueNDRangeKernel(command_queue, kernel, 1, NULL, &global_data_size, NULL, 0, NULL, NULL);
ret = clEnqueueMarker(command_queue, &event);
clWaitForEvents(1, &event);
printf("Return: %d\n", ret);
size_t time = 777;
ret = clGetEventProfilingInfo(event, CL_PROFILING_COMMAND_END, sizeof(time), &time, NULL);
printf("Return: %d\n", ret);
printf("Barrier time: %lu usec\n", time / 1000);
```
で
@ titanv
```
Return: 0
Return: 0
Barrier time: 1569576034935503 usec
```
@ vega
```
Return: 0
Return: 0
Barrier time: 185001897727 usec
```
になりました、これで測れていそうな気がします

**Comment by LWisteria** [comment]
`clEnqueueBarrierWithWaitList` がダメな理由はちょっと謎ですが、とりあえず今の状況だとMarkerの方が正しいと思うので、それに変更をお願いします

**Comment by shusukeueda** [comment]
変更します。ありがとうございます

**Comment by shusukeueda** [comment]
#251 で、titanv でも時間測れるようになりました。
例によってゆらぎますが、m = n = k  = 500、titanv、ClPy で
SGEMM: 0.95 msec / clpy.dot 0.36 msec (± 20 μsec)

SGEMM が vega より遅い？

**Comment by LWisteria** [comment]
vega clpyの結果が変わったりしてませんか？

**Comment by LWisteria** [comment]
あと、せっかくなので、3条件の結果をまとめて表示してほしいです。

**Comment by shusukeueda** [comment]
vega-ClPy の SGEMM も長いほうに揺らいだりすることがあるので微妙ですが、
長くても 0.8 msec くらいなので、有意に titanv + ClPy + SGEMM が遅そうです。

**Comment by shusukeueda** [comment]
#251 の後で、m = n = k = 500 で
vega、ClPy
SGEMM 0.68 msec / clpy.dot 0.38 msec

titanv、CuPy
SGEMM 0.55 msec / cupy.dot 0.25 msec

titanv、ClPy
SGEMM 0.95 msec / clpy.dot 0.36 msec

正確に統計とってないのでわかりませんが、長いほうに + 0.15 msec くらい揺れることがあります
基本的には SGEMM < cp.dot で、
SGEMM については titanv CuPy < vega ClPy < titanv ClPy、
cp.dot については titanv CuPy < titanv ClPy = vega ClPy
な感じがあります。

**Comment by LWisteria** [comment]
ありがとうございます。移植と計測終わったので、閉じます！
