### ISSUE TITLE
Ultima doesn't accept functions named half

### ISSUE THREAD

**Issue by vorj** [fixstars/clpy#238]
https://github.com/fixstars/clpy/pull/236#issuecomment-511706588

**Comment by vorj** [comment]
It seems that supporting `half` as type is the cause of this issue. So, I think that we need to solve #224 at first.

**Comment by LWisteria** [comment]
This is not needed to support. won't fix

**Comment by vorj** [comment]
see: https://github.com/fixstars/clpy/pull/236#issuecomment-511727805
