### ISSUE TITLE
Fix the LLVM path configurations in the Developer's tutorial and README

### ISSUE THREAD

**Issue by ybsh** [fixstars/clpy#245]
The current instructions lead to a build failure of ClPy. Fixing.

**Comment by ybsh** [comment]
I created pull request for the README.md modificaion: https://github.com/fixstars/clpy/pull/248
When it has been merged, I will change the wiki (Developer's Tutorial) so that its LLVM/Clang instruction references the README.md.

**Comment by ybsh** [comment]
@LWisteria Please check the pull request.

**Comment by ybsh** [comment]
@LWisteria Thank you. Changing the wiki.

**Comment by ybsh** [comment]
@LWisteria Is it OK for us to have titanv's LLVM install path publicly on the wiki?

**Comment by LWisteria** [comment]
No problem. But please note that it is an example for someone (i.e. a fixstars member who uses the primary machine).

**Comment by ybsh** [comment]
OK. Thank you.

**Comment by ybsh** [comment]
Updated the section. https://github.com/fixstars/clpy/wiki/Developer's-tutorial#2-llvmclang
I will close this if there seems to be no problem.

**Comment by ybsh** [comment]
Updated the section. https://github.com/fixstars/clpy/wiki/Developer's-tutorial#2-llvmclang
@LWisteria Please close this if there seems to be no problem.

**Comment by LWisteria** [comment]
Thank you!
