### ISSUE TITLE
Possible performance improvement with fewer NumPy core function calls

### ISSUE THREAD

**Issue by ybsh** [fixstars/clpy#257]
As a result of experiments and analyses starting from [here](https://github.com/fixstars/clpy/issues/153#issuecomment-540330737) to [here](https://github.com/fixstars/clpy/issues/153#issuecomment-540476097), it turned out
NumPy calls are more frequently called and take longer than CuPy by some seconds, in one of Chainer's sample program ```train_mnist.py```.

 If you can reduce ClPy's calling frequency of those functions, ClPy's runtime is likely to be shortened. Is this possible without losing functionality?

(Note: the reports above are results of just one sample program.)

**Comment by ybsh** [comment]
According to [this comparison](https://github.com/fixstars/clpy/issues/153#issuecomment-548202563) between CuPy and ClPy function calls and their [call graphs](https://github.com/fixstars/clpy/issues/153#issuecomment-540464964),
```max```, ```sum```, ```mean```, etc. of CuPy ```ndarray``` do **NOT** instantiate NumPy's ```_ctypes``` object, while ClPy's counterparts do, entailing a relatively time-consuming function call subtree.

**Comment by ybsh** [comment]
I'm trying to find out where the instantiations are happening.

**Comment by ybsh** [comment]
Should be [here](https://github.com/fixstars/clpy/blob/08d1e628db0abfe7bbff9d0ea891d8cdfcc6396e/clpy/backend/function.pyx#L104).
I need to know if this can be eliminated.
I'd really appreciate it if someone familiar with this portion of code could tell me some instant thought about this.

**Comment by ybsh** [comment]
Here is a little more detailed call graph than the one shown before.
![clpy_detail](https://user-images.githubusercontent.com/40310171/67936455-2cedc600-fc0f-11e9-904b-fd1cd60b3a43.png)

**Comment by ybsh** [comment]
I have obtained this graph by adding the ```# cython: profile=True ``` directive to
- ```backend/function.pyx```
- ```core/core.pyx```
- ```core/elementwise.pxi```
- ```core/reduction.pxi```

**Comment by ybsh** [comment]
That line of code, as endorsed by a developer, was written for the sake of getting raw pointers of scalar values to be given to OpenCL kernel as arguments. As a result, a ```_ctypes``` is instantiated for every scalar argument in every kernel call.

**Comment by ybsh** [comment]
That line of code, as endorsed by a developer (@nsakabe-fixstars), was written in order to get raw pointers of scalar values to be given to OpenCL kernels as arguments. As a result, one ```_ctypes``` is instantiated for every scalar argument in every kernel call.

**Comment by ybsh** [comment]
If raw pointers of scalar arguments can be obtained through Cython feature [as done for the indexer in the previous lines](https://github.com/fixstars/clpy/blob/08d1e628db0abfe7bbff9d0ea891d8cdfcc6396e/clpy/backend/function.pyx#L83), we could avoid the overhead. I'll look into if they can.

**Comment by ybsh** [comment]
I'm stuck figuring out what type of scalar arguments exactly should be supported.
Only plain Python objects such as ```int``` and ```float```? What about NumPy scalars? If so, which of them?
If CuPy has specs we should conform to it. I checked [CuPy's doc on user-defined kernels](https://docs-cupy.chainer.org/en/stable/reference/kernel.html) but it doesn't seem to define exact parameter types there. Does anyone have a view on this?

**Comment by ghost** [comment]
@ybsh 

Are [these lines of code in CuPy](https://github.com/cupy/cupy/blob/v2.1.0/cupy/core/elementwise.pxi#L37-L83) significant?

See also [elementwise.pxi/_preprocess_args(args)](https://github.com/cupy/cupy/blob/v2.1.0/cupy/core/elementwise.pxi#L117)

**Comment by LWisteria** [comment]
@ybsh Is [this numpy document](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html) enough for you?

**Comment by ybsh** [comment]
@nsakabe-fixstars @LWisteria Thank you! Now I see the goal clearly: to support as much of the NumPy specs as possible (which also is the goal of CuPy).

**Comment by ybsh** [comment]
I could eliminate [the heavy ```ctypes``` instantiation (marked "here")](https://github.com/fixstars/clpy/issues/257#issuecomment-548290777) by 
[usuing a different NumPy interface](https://github.com/fixstars/clpy/compare/cc72c544a17c...7290654b970d).
This reduced ```train_mnist.py``` runtime by around 20% (from 56 s to 45 s. no profile / no synchronization)

As for testing, the mentioned commit passed the automated CI test, and I have run the following and I think I've got it passed:
```
$ python -m pytest dev/clpy/clpy/tests/example_tests/test_gemm.py
================================================ test session starts =================================================
platform linux -- Python 3.6.5, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /(HOME)/(DEVDIR)/dev/clpy/clpy, inifile: setup.cfg
collected 1 item

dev/clpy/clpy/tests/example_tests/test_gemm.py .                                                               [100%]

================================================= 1 passed in 1.06s ==================================================
```

If there are something more I should check, please inform me.

**Comment by ybsh** [comment]
![Call graph after the modification](https://user-images.githubusercontent.com/40310171/68364297-ddf4e300-0170-11ea-8085-c63d9a5efd72.png)

**Comment by LWisteria** [comment]
@ybsh Why don't you send (WIP/draft) PR and comment it? Now nobody other than you can't know that which modification you are discussing.

**Comment by ybsh** [comment]
@LWisteria Sorry I was late in reporting my current state. I was still looking into the source code because I thought further optimization could be possible.

**Comment by ybsh** [comment]
I haven't eliminated [```issctype``` call](https://github.com/fixstars/clpy/blob/08d1e628db0abfe7bbff9d0ea891d8cdfcc6396e/clpy/backend/function.pyx#L103), which is taking 1% of the runtime (around 0.5s).

CuPy does not call ```isctype``` so I looked into [CuPy's code] for optimization hints, but I found they were using another NumPy interfaces, which means they also are likely to be paying costs. https://github.com/cupy/cupy/blob/4867ff1a0245ec5c49d75465ad1625ac8ab4baa4/cupy/cuda/function.pyx#L94-L104 .

I don't think we can make notable difference by imitating their implementation, so I'll stop here.

**Comment by ybsh** [comment]
I'll create a pull request.

**Comment by ybsh** [comment]
It was easier than I first thought to inco

**Comment by ybsh** [comment]
I eliminated the ```issctype``` call too, so I'll make a pull request with this change included.

**Comment by ybsh** [comment]
@LWisteria I have created a PR. I'd appreciate your review.
https://github.com/fixstars/clpy/pull/258/
