### ISSUE TITLE
Deprecated GitHub API use

### ISSUE THREAD

**Issue by ghost** [fixstars/clpy#263]
https://github.com/fixstars/clpy/blob/7b800fefe60bffae1a1d6df90f350ecd5f78ec27/jenkins/post_comment.sh#L39

We should use `curl -u {username}:{access_token} {endpoint}` instead.

See also: https://developer.github.com/v3/auth/#via-oauth-and-personal-access-tokens

**Comment by vorj** [comment]
[It](https://github.com/fixstars/clpy/pull/262/commits/8dac3b0447f0a338aabe653b2685879d56b91581) [works](https://github.com/fixstars/clpy/pull/262#pullrequestreview-352819947) [fine](https://github.com/fixstars/clpy/pull/262#pullrequestreview-352822485).

**Comment by vorj** [comment]
#262 had solved this issue.
