### ISSUE TITLE
Removing cl_khr_fp16

### ISSUE THREAD

**Issue by LWisteria** [fixstars/clpy#264]
As of #224 and #261, the current solution for "half" needs cl_khr_fp16.

However, it must not need it theoretically and could be removed.

**Comment by LWisteria** [comment]
It was inserted on ac3adc9204633fc3a5c9938728357c8214ce138c to solve #131 .

@vorj @nsakabe-fixstars Can you remember and explain the reason?
I remember the reason is just to avoid the problem that sqrt of int8 and int16 is stored as the half format.
It is not enough to prove its necessity because only storing half format uses no half operation which needs to set cl_khr_fp16.

**Comment by vorj** [comment]
> int8 and int16

No, problematic types are `int8` , `uint8` , and `bool` . Some functions have only floating type(s) for input/output , then the types are converted to `half` .
`int16` is converted to `float` , so it has no problem.
[The problematic functions list](https://github.com/fixstars/clpy/pull/225#issuecomment-495089099) has been shown as test cases that are failed when we disable `cl_khr_fp16` ,  by @nsakabe-fixstars.

> It is not enough to prove its necessity because only storing half format uses no half operation which needs to set cl_khr_fp16.

I really think so, **but [NVIDIA doesn't](https://github.com/fixstars/clpy/pull/131#discussion_r243175286)** .

**Comment by LWisteria** [comment]
@vorj Thanks. 

Your previous comment

> In OpenCL C on NVIDIA GPU, enabling cl_khr_fp16 is required to copy a half value.

must be checked on the current titanv (CUDA 10). 

Furthermore, to solve the problem with only the copy operation, for example, we can treat fp16 as int16. I remember there were some reasons to disturb such solutions but I don't remember what they actually were.

Anyway, I don't think that investigation for the solution to avoid it is perfect. The priority to pass the tests was higher than enough investigation at that time. 
Now it's time to try it...!

**Comment by vorj** [comment]
> Your previous comment
>
>> In OpenCL C on NVIDIA GPU, enabling cl_khr_fp16 is required to copy a half value.
>
> must be checked on the current titanv (CUDA 10). 

Please see [the secondary machine error log for #260 ](https://github.com/fixstars/clpy/issues/261#issuecomment-581262047).
I've shown the extracts of the errors below:

```
warning: cannot enable cl_khr_fp_16 extension on this platform - ignoring.
error: declaring function return value of type 'half' is not allowed; did you forget * ?
error: loading directly from pointer to type 'const __attribute__((address_space(16776963))) half' is not allowed
``` 

It seems that NVIDIA doesn't allowed to copy `half` value yet (`cl_khr_fp16 enable` is just ignored). Originally we use `cl_khr_fp16` only to enable copying and we've never added `half` arithmetic operations, so it's obvious. Of course, we can pass the test cases without enabling `cl_khr_fp16` on the primary machine.

**Comment by vorj** [comment]
#269 fixed this issue, so I close it.
