### ISSUE TITLE
Type mismatch of rand implementation `clpy_expand_inner_state_array`

### ISSUE THREAD

**Issue by y1r** [fixstars/clpy#272]
Rand kernel expects ulong value for `stride` (https://github.com/fixstars/clpy/blob/clpy/clpy/backend/opencl/random.pyx#L41)
However, python integer is passed to kernel.
(https://github.com/fixstars/clpy/blob/clpy/clpy/backend/opencl/random.pyx#L148)

**Comment by ghost** [comment]
#283 has resolved this.
