### ISSUE TITLE
test commands help

### ISSUE THREAD

**Issue by jinz2014** [fixstars/clpy#273]
Can you please list the specific commands to run the tests available in the repository after the installation of clPy ?  

Thanks

**Comment by ghost** [comment]
@jinz2014 

Could you see [clpy/jenkins/build_and_test.sh](https://github.com/fixstars/clpy/blob/50ee94b7d8cdf020e1fcfeb10802e3f06e48f8d0/jenkins/build_and_test.sh)? It's a script we use to perform continuous integration.

[Here](https://github.com/fixstars/clpy/blob/50ee94b7d8cdf020e1fcfeb10802e3f06e48f8d0/jenkins/build_and_test.sh#L40-L68) are lists of available test files.
You can run them with `python -m pytest <file name or directory name>` [like this](https://github.com/fixstars/clpy/blob/50ee94b7d8cdf020e1fcfeb10802e3f06e48f8d0/jenkins/build_and_test.sh#L76).

**Comment by jinz2014** [comment]
Thanks. I will close the issue.
