### ISSUE TITLE
permutation 

### ISSUE THREAD

**Issue by jinz2014** [fixstars/clpy#274]
Can you please add the function clpy.random.permutation in clpy ?  I think it is useful for randomization. 

Thanks

**Comment by ghost** [comment]
Hi, @jinz2014 

Thank you for your suggestion.
[The based repository, CuPy, implemented `random.permutation` at `version 4.0.0b3`](https://github.com/cupy/cupy/commit/c2980c55d8db636c4c9db651962a5d6343a4dac7), while our forked version is `2.1.0` yet.
We plan to upgrade our version in Issue https://github.com/fixstars/clpy/issues/33 .
`clpy.random.permutation` will be available after that.

**Comment by jinz2014** [comment]
When the upgrade time is not certain, could you give some suggestions on  how people can try to develop an OpenCL function (e.g. clpy.random.permutation) based on the CUDA implementation ?  In other words, it is helpful to have a guide for people, who do not have experience with mixing Python and OpenCL, to add new functions.  

Thanks

**Comment by vorj** [comment]
@jinz2014,

Do you have some experiences to create your own `ElementwiseKernel` on CuPy?
ClPy also has the `clpy.ElementwiseKernel` interface, so we can create our own `ElementwiseKernel` in the basically same way as CuPy.
ClPy contains [_Ultima_](https://github.com/fixstars/clpy/blob/clpy/ultima/ultima.cpp) , the code converter from CUDA C++ **for CuPy** to OpenCL C **for ClPy** (it means that _Ultima_ doesn't support full set of C++ as input), so you can use some C++ constructs like [`reinterpret_cast`](https://github.com/cupy/cupy/commit/c2980c55d8db636c4c9db651962a5d6343a4dac7#diff-bdf8bf88a45064e9d8d316ebd0d0f6fbR369-R370) on `clpy.ElementwiseKernel` .
When you will implement `random.permutation` porting from [CuPy implementation](https://github.com/cupy/cupy/commit/c2980c55d8db636c4c9db651962a5d6343a4dac7#diff-bdf8bf88a45064e9d8d316ebd0d0f6fbR349-R402) , you will need to implement [`atomicExch`](https://github.com/cupy/cupy/commit/c2980c55d8db636c4c9db651962a5d6343a4dac7#diff-bdf8bf88a45064e9d8d316ebd0d0f6fbR381) like [this](https://github.com/fixstars/clpy/blob/clpy/clpy/core/include/clpy/carray.clh#L504-L525).

BTW, 

> it is helpful to have a guide for people, who do not have experience with mixing Python and OpenCL, to add new functions.

We will think about it. Thank you for your proposal.

**Comment by jinz2014** [comment]
Sorry, I don't fully understand the role of Ultima. Do people need to manually convert CUDA C++ for CuPy to OpenCL C for ClPy by running some Ultima executable ?  I will try to create my own Elementwise kernel on CuPy, and try to understand how to port an implementation from CUDA to OpenCL. 

Thanks

**Comment by LWisteria** [comment]
@jinz2014 You don't need to think about differences between CuPy (CUDA) and ClPy (OpenCL) when you just use ClPy, including making a custom kernel. Because current ClPy is (almost) compatible with CuPy, you have nothing to do on your CuPy codes. ClPy (including Ultima) makes them good automatically.

That's why @vorj suggest you writing CuPy codes. If you find some problems with your CuPy (v2.1.0) codes, that's could be a bug.

**Comment by vorj** [comment]
@jinz2014

> Do people need to manually convert CUDA C++ for CuPy to OpenCL C for ClPy by running some Ultima executable ?

No, ClPy executes Ultima **automatically** before compiling `ElementwiseKernel` .

Ultima had been originally developed to support Chainer.
Since Chainer gives C++ codes to `ElementwiseKernel` interface, `ElementwiseKernel` interface must support some C++ constructs used on Chainer to support Chainer.
However, generally we can use OpenCL C, but we can't use OpenCL C++.
Thus we had created Ultima.
ClPy with Ultima converts codes from CUDA C++ for CuPy to OpenCL C for ClPy automatically .

> how to port an implementation from CUDA to OpenCL

As above description and @LWisteria said, basically you don't need to change your `cupy.ElementwiseKernel` codes for `clpy.ElementwiseKernel`.
Ultima converts them automatically.
However, Ultima doesn't support all of CUDA C++ constructs, so when you will be hit `clpy.backend.ultima.exceptions.UltimaRuntimeError` , please comment it.

**Comment by jinz2014** [comment]
Based on your guide, I implemented the permutation, but hit some issues.  Thanks for your review. 

/tmp/153690.834795972.cpp:21:50: error: 'continue' statement not in loop statement
        if (j == i || j < j_start || j >= j_end) continue;

I replaced 'continue' with 'return' in the core.ElementwiseKernel shown below to fix the issue. Is that right ? 

When I tested my implementation, the number of unique elements after permutation is less than 60000. So there are some bugs in my implementation, but I am not sure what could go wrong when  porting the cupy implementation.  

```
import clpy as cp
import numpy as np
r = cp.random.permutation(60000)
r_h = cp.asnumpy(r)
print(len(np.unique(r_h)))
```

I listed the source codes below for you to review the OpenCL implementation.

```
    def permutation(self, a):
        """Returns a permuted range or a permutation of an array."""
        if isinstance(a, int):
            return self._permutation(a)
        else:
            return a[self._permutation(len(a))]

    def _permutation(self, num):
        """Returns a permuted range."""
        sample = clpy.empty((num), dtype=numpy.int32)
        clrand.generate(self._generator, sample)
        if 128 < num <= 32 * 1024 * 1024:
            array = clpy.arange(num, dtype=numpy.int32)
            # apply sort of cache blocking
            block_size = 1 * 1024 * 1024
            while num // block_size > 12:
                block_size *= 2
            for j_start in range(0, num, block_size):
                j_end = j_start + block_size
                _clpy_permutation(sample, j_start, j_end, array, size=num)
        else:
            # When num > 32M, argsort is used, because it is faster than
            # custom kernel. See https://github.com/cupy/cupy/pull/603.
            array = clpy.argsort(sample)
        return array

_clpy_permutation = core.ElementwiseKernel(
    'raw int32 sample, int32 j_start, int32 _j_end',
    'raw int32 array',
    '''
        const int invalid = -1;
        const int num = _ind.size();
        int j = (sample[i] & 0x7fffffff) % num;
        int j_end = _j_end;
        if (j_end > num) j_end = num;
        if (j == i || j < j_start || j >= j_end) return;    
        int j_offset = ((2*j - i + num) % (num - 1)) + 1;
        int loops = 256;
        bool do_next = true;
        while (do_next && loops > 0) {
            // try to swap the contents of array[i] and array[j]
            if (i != j) {
                //int val_j = atomicExch(&array[j], invalid);
                int val_j = atomic_cmpxchg(&array[j], array[j], invalid);
                if (val_j != invalid) {
                    //int val_i = atomicExch(&array[i], invalid);
                    int val_i = atomic_cmpxchg(&array[i], array[i], invalid);
                    if (val_i != invalid) {
                        array[i] = val_j;
                        array[j] = val_i;
                        do_next = false;
                        // done
                    }
                    else {
                        // restore array[j]
                        array[j] = val_j;
                    }
                }
            }
            j = (j + j_offset) % num;
            loops--;
        }
    ''',
    'clpy_permutation',
) 
```

**Comment by ghost** [comment]
@jinz2014 

How about using [atomic_xchg](https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/atomic_xchg.html) instead of atomic_cmpxchg?
I guess the latter needs confirmation of exchanging result (success/failed).

**Comment by jinz2014** [comment]
It passes the test listed above.  I am confused about the pull request. Maybe I can send you an email for my code changes.

**Comment by ghost** [comment]
@jinz2014 

Thank you for your proposition. Since `random.permutation` will be merged from upstream in the _near_ future, you don't need to send it us.

Sincerely,
