### ISSUE TITLE
Support LLVM 10

### ISSUE THREAD

**Issue by vorj** [fixstars/clpy#284]
LLVM 10.0.0 has been released. ~~We should support it.~~ I wanna support it.

**Comment by vorj** [comment]
Since LLVM 10.0.0, Clang API requires C++14. So, both ultima and headercvt need to be fixed.

**Comment by LWisteria** [comment]
Do you/we really need to support v10? Why not v9 or v11 or later?

**Comment by vorj** [comment]
> Why not v9 or v11 or later?

What do you mean? We already support v9, and v11 or later have not been released.

**Comment by LWisteria** [comment]
Who wants/needs LLVM v10 to run ClPy and why?

* v9 is not enough? How?
* Do many users want to run on the newest LLVM?
* Even if yes, they will need the later version when they try to use ClPy. They want to support the version they want, not v10. Why do you think that supporting v10.0.0 is really needed by them? (and why we should provide)

**Comment by vorj** [comment]
IMO, it is hard to maintain the environment contains two or more versions of LLVM/Clangs.
When the program using LLVM/Clang internally doesn't limit the LLVM/Clang's version, we don't need to maintain many versions.
So, it is better to support more versions than to limit the version in general.

> Who wants/needs LLVM v10 to run ClPy and why?

At least I want to do that.

> v9 is not enough? How?

Of course it's enough to realize ClPy's feature.
v4-v8 are also enough.
However, when I will install v10, I won't want to preserve the old toolset only to use ClPy, because the maintenance cost is not low.

> Do many users want to run on the newest LLVM?

I don't know because I have no data about ClPy's users.
However, they will definitely show up in the future.

> Even if yes, they will need the later version when they try to use ClPy. They want to support the version they want, not v10. Why do you think that supporting v10.0.0 is really needed by them? (and why we should provide)

Is this sentence related to "v11 or later" ?
If so, you might wonder why I created the issue only for v10 but not one for v11 or later.
The answer is very simple. We can't know how Clang's API will be broken before they will be released.
We have no choice but to investigate how the API is broken in every release.

**Comment by LWisteria** [comment]
> it is hard to maintain the environment contains two or more versions of LLVM/Clangs.

yes, but

> it is better to support more versions than to limit the version in general.

Why should we? Is it the best solution we should do? Supporting the newer version is needed only when our computers are updated, not now, not v10.

> At least I want to do that.

That means "you want to support (for your interest)", not "we should support (to develop ClPy)".

**Comment by vorj** [comment]
>not now, not v10.

OK, so let's consider the situation when LLVM/Clang has been updated from v9 to v11 in our computers for example.
We need to add some workarounds to support many versions when some APIs are broken, so we will add some workaround to support v11.
Of course there is no guarantee that ClPy supporting v11 supports v10, because we hasn't implemented the workarounds for v10.
Do you think that ClPy should support v9 and v11 but not v10?
It seems curious for me.

> That means "you want to support (for your interest)", not "we should support (to develop ClPy)".

That's make sense. I fixed the description.

**Comment by vorj** [comment]
#291 solved this issue. See you in the next LLVM release :wave:
