### ISSUE TITLE
cnn framework implemented in pure numpy interface. (need help for performance)

### ISSUE THREAD

**Issue by yxdragon** [fixstars/clpy#286]
Hi, I 'd like to tell you, we wrote a cnn framework [Planer](https://github.com/Image-Py/planer) based on pure numpy-interface (with out any kernel code or jit code). And it could be set core with cupy or clpy to get a better performance.

We had try some demos, such as [craft text detector](https://github.com/Image-Py/planer/blob/master/demo/craft_text_detector/main.py). and here is the report.
planer with numpy core: 14s
planer with clpy core: 7s
planer with cupy core: 0.15s 
pytorch with gpu: 0.19s
(cupy core has a equal performance with torch, 1-3 times slower, in some model even is faster than torch)

Is this a normal result? I can accept a 1-5 times slower, but now it is a 50 times.
(the all operation in planer is + * reshape, transpose, pad, zeros, dot, exp, clip).

As most of dl frame work works with cuda, and now clpy has no cudnn like function. So I think Planer is meaningful, So I need help to improve the performance.

**Comment by ghost** [comment]
Hi, @yxdragon 

Thank you for trying ClPy with Planer.
I agree that the performance you got is not regular.

Could you confirm that ClPy's computation is running on your GPUs?
Available platforms can be enumerated with [clinfo](https://github.com/Oblomov/clinfo).
If there are 2 (or more) platforms, ClPy unfortunately uses the first one.
CPU parallelization or CPU-integrated GPU one may provide such a little speedup.

Thanks to your feedback, we get to know that the way to specify platform is needed.

**Comment by yxdragon** [comment]
hi, @nsakabe-fixstars 
unfortunately, follow your advice, the program run on GPU.
![image](https://user-images.githubusercontent.com/24822467/79640706-91084480-81c5-11ea-94a3-adc7d13462dc.png)
![image](https://user-images.githubusercontent.com/24822467/79640709-96658f00-81c5-11ea-8f14-9d49afe663d3.png)

if your computer has clpy and cupy both, could you help to do a test?
here is the [craft](https://github.com/Image-Py/planer/blob/master/demo/craft_text_detector/main.py) demo, 

just modify:
import planer, clpy or cuda
pal = planer.core(clpy or cuda)

**Comment by y1r** [comment]
Hi @yxdragon,
Thank you for trying ClPy.
I've tried Planer with ClPy but there is no significant performance degrade.
Environments:
- Planer (d233355f17bca77c500a3c1b8aaa59b6318ea9d0)
  - I modified a part of `planer/io.py` to enable `net.load_weights` with random initialization (because I cannot access craft.npy).
- ClPy (bb59e0aa43d83c964d7edb3450fa1e70b758aff7)
- CuPy (4867ff1a0245ec5c49d75465ad1625ac8ab4baa4), without cuDNN
```
NumPy:
load done!
start timing!
planer craft time (x10): 4.103426694869995
conv 3.2610843181610107
batchnorm 0.13772082328796387
relu 0.10482430458068848
maxpool 0.4480116367340088
concat 0.022514820098876953
upsample 0.08834123611450195
return 2.1696090698242188e-05
```
```
CuPy without cuDNN:
load done!
start timing!
planer craft time (x10): 0.6608967781066895
conv 0.3601830005645752
batchnorm 0.09809494018554688
relu 0.034891366958618164
maxpool 0.03769659996032715
concat 0.0061914920806884766
upsample 0.09757781028747559
return 1.3828277587890625e-05
```
```
ClPy:
load done!
start timing!
planer craft time (x10): 0.5804731845855713
conv 0.38742542266845703
batchnorm 0.09003186225891113
relu 0.033240556716918945
maxpool 0.00956273078918457
concat 0.006394624710083008
upsample 0.0275876522064209
return 1.3113021850585938e-05
```
I want to reproduce your situation. Could you tell me commit ids of ClPy and CuPy?

**Comment by LWisteria** [comment]
We could not reproduce the reported problem, and the reporter has not provided further information.
