### ISSUE TITLE
bad performance and CPU usage is 100%

### ISSUE THREAD

**Issue by be-thomas** [fixstars/clpy#289]
So, I compared clpy with numpy.
And the results seem unimpressive.
numpy is always faster even when performing lots of operations, that too on a huge array.

Also, I was skeptical to see one of my logical cores to stick at 100% usage both when using NumPy as well as CLPy.
Is it running on my CPU? how do I switch devices?

this is my numpy code -
```
import numpy as cl

a, b = cl.empty((1000,1000), dtype=cl.float64), cl.empty((1000,1000), dtype=cl.float64)

start = time.time()
c = a * 5; c += b; c *= a; c *= 10; c -= a
for x in c: print(x)
end = time.time()

diff = end - start
print(diff*1000)
```

numpy benchmark -
![Screenshot_2020-09-13_20-12-47](https://user-images.githubusercontent.com/36351384/93020912-8380aa80-f5fd-11ea-8d4b-69ba17fced30.png)

1 logical core reached 100% usage while the numpy benchamark is running(this is expected behaviour) -
![Screenshot_2020-09-13_20-16-00](https://user-images.githubusercontent.com/36351384/93020991-fdb12f00-f5fd-11ea-8747-8a0fecc6606f.png)

this is my clpy code -
```
import clpy as cl

a, b = cl.empty((1000,1000), dtype=cl.float64), cl.empty((1000,1000), dtype=cl.float64)

start = time.time()
c = a * 5; c += b; c *= a; c *= 10; c -= a
for x in c: print(x)
end = time.time()

diff = end - start
print(diff*1000)
```

clpy benchmark -
![Screenshot_2020-09-13_20-10-21](https://user-images.githubusercontent.com/36351384/93020891-664bdc00-f5fd-11ea-98bd-f9f61f086477.png)

1 logical core reaches 100% while the clpy benchmark is running -
![Screenshot_2020-09-13_20-14-51](https://user-images.githubusercontent.com/36351384/93020970-e5411480-f5fd-11ea-8a26-1840c946e304.png)

I suppose, it should not reach 100% usage when using CLPy.
Also, background apps are not the culprit for high cpu usage. because as soon as the benchmark ends,
this is the cpu usage -
![Screenshot_2020-09-13_20-21-16](https://user-images.githubusercontent.com/36351384/93021124-b11a2380-f5fe-11ea-9fdb-64b2312691d9.png)

This is the partial output of clinfo -
![Screenshot_2020-09-13_20-22-31](https://user-images.githubusercontent.com/36351384/93021147-e292ef00-f5fe-11ea-9317-f989e708a639.png)

I have i3-6006U with Intel HD 520 (integrated GPU). I am expecting at least some performance improvement.
It has 4 threads(4 logical cores, 2 physical cores).

Can you please help me with this ?

**Comment by ghost** [comment]
There are some improvements on your benchmark code, I guess.

1. `c = a * 5` (without declaration/initialization) includes allocation of OpenCL memory object. Declare it in advance like as `a` and `b`.
1. Every time of `for x in c` iteration issues device-to-host transfer. Exclude transfer time from measurement, or consider using [`clpy.asnumpy`](https://docs.cupy.dev/en/v2.5.0/reference/generated/cupy.asnumpy.html).

**Comment by rdguerrerom** [comment]
Hi, 

Is this issue still open?

**Comment by LWisteria** [comment]
The problem is on the reported (user's) benchmark code, not caused by clpy itself.
