### ISSUE TITLE
Specify Opencl Version during compile time

### ISSUE THREAD

**Issue by TheSeriousProgrammer** [fixstars/clpy#290]
I am trying to compile clpy on an ARM Soc. During compile time I get this warning message so I halted

/usr/include/CL/cl_version.h:34:104: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
 on.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")

My SOC supports OpenCL 1.2 

Should I ignore the warning and proceed? If I proceed will I face any errors due to version mismatch??

Thanks In Advance

**Comment by nsakabe-fixstars** [comment]
`CL_TARGET_OPENCL_VERSION` is defined to 

https://github.com/KhronosGroup/OpenCL-Headers#compiling-for-a-specific-opencl-version

**Comment by ghost** [comment]
You can ignore the warning.
Defining `CL_TARGET_OPENCL_VERSION` forces the users (in this case, us, _clpy_) not to use APIs above the specified version.
We use OpenCL 1.2 features so it's going well in your environment.

https://github.com/KhronosGroup/OpenCL-Headers#compiling-for-a-specific-opencl-version

Anyway, we consider adding `CL_TARGET_OPENCL_VERSION` definition.

Thanks,

**Comment by TheSeriousProgrammer** [comment]
Thanks , It worked fine! It was just a warning
