### ISSUE TITLE
Generate OpenCL API wrapper from cl.h in system

### ISSUE THREAD

**Issue by LWisteria** [fixstars/clpy#3]
[Current api.pxd](https://github.com/fixstars/clpy/blob/dec25c342032617d61e6b71ad5836b16005cc29a/clpy/backend/opencl/api.pxd) and api.pyx was manually made by header for OpenCL 1.2.

The API wrapper can and must be generated from cl.h corresponding to system installing and/or executing.

**Comment by LWisteria** [comment]
Relate: #2

**Comment by ghost** [comment]
@nsakabe-fixstars お願いします！

**Comment by ghost** [comment]
### `api.pxd`

* `cdef extern from "CL/cl.h":`
    * 関数宣言すべて (`/cl[A-Z][a-zA-Z_]+/`)
        * :heavy_check_mark: 
* 薄い wrapper の宣言 (生成の必要なし)

### `types.pxi`
* `cde extern from "CL/cl.h":`
    * `cdef enum:`
        * `#define` によるコンパイル時定数すべての名前 (`/CL_[a-zA-Z_]+/`)
        * :heavy_check_mark: 
    * `ctypedef T1 T2` (T2: 標準ヘッダの `u?intNN_t`, `size_t`, `ptrdiff_t` など, そして `__cl_.*`, `cl_.*`)
        * :heavy_check_mark: 
    * `cdef struct T: pass` : ポインタだけ使っていることで自然発生する宣言 :heavy_check_mark: 
    * `ctypedef struct T: メンバ変数....` :heavy_check_mark: 
    * union は無視 :heavy_check_mark:

**Comment by ghost** [comment]
とりあえず libClang の Python binding でいじってみます。

**Comment by ghost** [comment]
関数宣言がとれた
```shell-session
$ python headergen.py
   FUNCTION_DECL :  clGetPlatformIDs(cl_uint, cl_platform_id *, cl_uint *)
   FUNCTION_DECL :  clGetPlatformInfo(cl_platform_id, cl_platform_info, size_t, void *, size_t *)
...
```

**Comment by ghost** [comment]
Typedef_Decl がとれたが、attributeがついてる
```
   TYPEDEF_DECL : typedef  __attribute__((__vector_size__(1 * sizeof(cl_long)))) cl_long   __cl_long1
   TYPEDEF_DECL : typedef  __attribute__((__vector_size__(2 * sizeof(cl_float)))) cl_float   __cl_float2
   TYPEDEF_DECL : typedef  union cl_char2   cl_char2
   TYPEDEF_DECL : typedef  union cl_char4   cl_char4
   TYPEDEF_DECL : typedef  union cl_char8   cl_char8
...
```

現状の types.pxi ではattributeは単純に無視されている

**Comment by ghost** [comment]
### 現状
libTooling で AST のトラバースができるようになり、ほしい情報の取得と出力フォーマット合わせを行っている

### メモ
`typedef struct *a a;`  
などが not handled に流れてくる理由: headercvt.cpp:447 あたりで Elaborated Type を持っているときベクタに突っ込んでcontinueするような操作をしているから。

やること:

* DeclGroup をうまく処理できるように `clang::Decl::printGroup` をもってきて visitor に渡すように改変する


AST エスケープシーケンスなしダンプ:

```shell-session
$ clang -Xclang -ast-dump -fsyntax-only stub.c -I/usr/local/cuda/include -I/usr/local/include -I/usr/include -I/usr/include/x86_64-linux-gnu -I/usr/local/lib/clang/6.0.0/include -fno-color-diagnostics | vim -
```

**Comment by ghost** [comment]
`typedef struct _hoge* hoge_t;` (事前の `struct _hoge` 宣言なし)
↓
```
|-RecordDecl 0x54dd690 <hoge.c:2:9, col:16> col:16 struct _hoge
|-TypedefDecl 0x55366d0 <col:1, col:23> col:23 hoge_t 'struct _hoge *'
| `-PointerType 0x5536680 'struct _hoge *'
|   `-ElaboratedType 0x5536620 'struct _hoge' sugar
|     `-RecordType 0x5536600 'struct _hoge'
|       `-Record 0x54dd690 '_hoge'
```

この RecordDecl と TypedefDecl が Group 化されて、processDeclGroupにかけられる

**Comment by ghost** [comment]
`typedef struct {} type_name` 型
↓
```
|-RecordDecl 0x55ae7f0 </usr/include/x86_64-linux-gnu/bits/typesizes.h:72:24, col:47> col:24 struct definition
| `-FieldDecl 0x55ae920 <col:33, col:44> col:37 __val 'int [2]'
|-TypedefDecl 0x55ae9c0 </usr/include/x86_64-linux-gnu/bits/types.h:117:22, line:134:26> col:26 referenced __fsid_t 'struct __fsid_t':'__fsid_t'
| `-ElaboratedType 0x55ae970 'struct __fsid_t' sugar
|   `-RecordType 0x55ae880 '__fsid_t'
|     `-Record 0x55ae7f0 ''

```

**Comment by ghost** [comment]
struct系を変換できたので、あとは

* プリプロセッサ定数を適当にとる :heavy_check_mark: 
* `cdef extern from` でくくり、インデントを適切に :heavy_check_mark: 
* clpy に組み込む
    * `clang` コマンドラインに与える Include ディレクトリの列挙
    * 複数ファイルを出力することになるが、`headercvt` から直にやるか、パイプを経由するか → 直にその場に出力のあとコピー

**Comment by ghost** [comment]
敵:
* Record宣言中に登場する無名構造体宣言 → pthread関連,union関連無視
* タグ名とRecordの識別子が同じ宣言 → pthread無視
* `typedef <関数ポインタ型> hoge_t` → 無視
* `typedef struct _cl_mem *            cl_mem;` の `struct` を剥がす → 剥がした

**Comment by ghost** [comment]
### 現状
headercvt で生成した宣言群をファイルに出力し、 clpy のビルドが通った。

headercvt の実行を `clpy_setup_build.py` に組み込み、clpy のビルド時に自動適用するように変更中。libTooling はデフォルトのインクルードディレクトリをもたないため、何らかの方法で取得し、 `-I` を渡す必要がある。

### メモ
* インクルードディレクトリ関連 :heavy_check_mark: 
    * https://clang.llvm.org/docs/LibTooling.html#builtin-includes
    * `ignoring nonexistent directory "/home/<username>/repo/clpy/headercvt/../lib/clang/6.0.0/include"`  
このツールからの相対パスで探してミスってるみたい。
* コミットメッセージ 英語に (コミット履歴の整理) :heavy_check_mark: 
* コメント 英語に (コメントの整理) :heavy_check_mark: 
* リファクタリング
    * `Indent()` を private に :heavy_check_mark: 
    * `ostreams` 削除 :heavy_check_mark: 
    * clang/lib 由来の無関係なコード(C++文法対応など)を削除 :heavy_check_mark:

**Comment by ghost** [comment]
*titanv* で開発していたが、 *vega* で動かしたら:

`union _cl_image_desc::(anonymous at /usr/include/CL/cl.h:116:5)`

**Comment by LWisteria** [comment]
#43 resolved this issue. Thanks!
