### ISSUE TITLE
Odd CI failure

### ISSUE THREAD

**Issue by ghost** [fixstars/clpy#36]
vega 機で謎にCIが通らない問題調査用のissueです

**Comment by ghost** [comment]
https://streamhpc.com/blog/2013-04-28/opencl-error-codes/

Code | OpenCL Error Flag | Function(s) | Description
-- | -- | -- | --
-1001 | CL_PLATFORM_NOT_FOUND_KHR | clGetPlatform | No valid ICDs found

**Comment by ghost** [comment]
ICD(Installable Client Driver) とは、実行時に動的リンクされるドライバーのこと

`/etc/OpenCL/vendors` の中身:
* amdocl-orca64.icd
    * libamdocl-orca64.so
* amdocl-rocr64.icd
    * libamdocl-rocr64.so
* amdocl64.icd
    * libamdocl64.so

**Comment by ghost** [comment]
```
$ ldconfig -p | grep libamd
        libamdocl64.so (libc6,x86-64) => /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so
        libamdocl12cl64.so (libc6,x86-64) => /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl12cl64.so
        libamdocl-rocr64.so (libc6,x86-64) => /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-rocr64.so
        libamdocl-orca64.so (libc6,x86-64) => /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-orca64.so
```

**Comment by ghost** [comment]
`bash --login` とか  
`sudo su - clpy-jenkins-slave`  
で入った環境での実行などを試しました(再現せず)

**Comment by LWisteria** [comment]
https://www.khronos.org/registry/OpenCL/sdk/2.0/docs/man/xhtml/cl_khr_icd.html

**Comment by ghost** [comment]
```
[clpy_testing_vega] $ /bin/bash -x /tmp/jenkins8148011439672881024.sh
```

ログを見ると、実行のされ方自体はこういうことらしい…

**Comment by ghost** [comment]
```
+ /opt/amdgpu-pro/bin/clinfo
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
/tmp/jenkins8244099499131785503.sh: 3 行: 23225 中止                  (コアダンプ) /opt/amdgpu-pro/bin/clinfo
```

**Comment by ghost** [comment]
AMD 公式 OpenCL ドライバを使用すべきところ、 apt で入った他のものが見つかっていたことが問題だった。

* amdgpu-pro-uninstall によって公式ドライバ削除
* apt search の結果のなかからOpenCL関係するものを削除
* AMD サイトから公式ドライバをインストール
* opencl-headers だけ apt からインストール
* LIBRARY_PATH, LD_LIBRARY_PATH を `/opt/amdgpu-pro/lib/x86_64-linux-gnu/` に通す

解決したので閉じます。
