### ISSUE TITLE
Support multiple devices

### ISSUE THREAD

**Issue by LWisteria** [fixstars/clpy#4]
Current clpy uses [only first device](https://github.com/fixstars/clpy/blob/dec25c342032617d61e6b71ad5836b16005cc29a/clpy/backend/opencl/env.pyx#L30-L41). Device should be selectable.

**Comment by ghost** [comment]
Device version check routine in [env.pyx](https://github.com/fixstars/clpy/blob/clpy/clpy/backend/opencl/env.pyx)
should be improved after multi device support is in service.

**Comment by ghost** [comment]
Must be reverted after multi-device supported:
* https://github.com/fixstars/clpy/pull/128/commits/c68f10b4b27e90b8e3943df29844e67086014fdc
* https://github.com/fixstars/clpy/blob/cd2f8da865d760a43563f5bd826f7ea4b131734d/tests/clpy_tests/core_tests/test_scan.py#L31

**Comment by LWisteria** [comment]
#140 and #160 resolve this issue. Thanks for your contributing!
