### ISSUE TITLE
Support CArray member functions

### ISSUE THREAD

**Issue by vorj** [fixstars/clpy#51]
`CArray` class in CuPy has some member functions:
- [x] `int size() const`
- [x] `const ptrdiff_t* shape() const`
- [x] `const ptrdiff_t* strides() const`

Current ClPy doesn't support to use these member functions.

**Comment by LWisteria** [comment]
You should revert acf60b261a25aa0bfbe4c2a937915b22282f3484 when you resolve this issue.

**Comment by vorj** [comment]
It seems that supporting `size()` and `strides()` is not simple.
- Current `CArray` of ClPy doesn't have `size_` data member, so we can't return valid value with `CArray::size()` .
- Current `CArray::strides_` of ClPy has different value from `CArray::strides_` of CuPy.
  It seems that ClPy's one has number of elements, and [CuPy's one has number of bytes](https://docs-cupy.chainer.org/en/stable/reference/generated/cupy.ndarray.html#cupy.ndarray.strides).
  So, if we want to implement `strides()` , we need information about size of `CArray` element.

**Comment by vorj** [comment]
All of CArray member functions have been supported. This issue is resolved.
