### ISSUE TITLE
Pass all tests

### ISSUE THREAD

**Issue by vorj** [fixstars/clpy#64]
Current ClPy doesn't pass all tests in `tests` directory.
We should support, remove, or fix all tests.

- [ ] `clpy_tests`
    - [x] `binary_tests`
    - [x] `core_tests`
        - [x] `test_carray.py`
        - [x] `test_core.py`
        - [x] `test_cupy_aliased_ndarray.py`
        - [x] `test_elementwise.py`
        - [x] `test_flags.py`
        - [x] `test_function.py`
        - [x] `test_fusion.py`
        - [x] `test_internal.py`
        - [x] `test_ndarray.py`
        - [x] `test_ndarray_adv_indexing.py`
            - depends on `inclusive_scan`
        - [x] `test_ndarray_complex_ops.py`
            - related: #29
        - [x] `test_ndarray_contiguity.py`
        - [x] `test_ndarray_copy_and_view.py`
        - [x] `test_ndarray_elementwise_op.py`
            - without tests of multi device  (related: #4)
        - [x] `test_ndarray_get.py`
        - [x] `test_ndarray_indexing.py`
        - [x] `test_ndarray_owndata.py`
        - [x] `test_ndarray_reduction.py`
        - [x] `test_ndarray_scatter.py`
            - depends on `inclusive_scan`, `scatter_add` for not only float32
        - [x] `test_ndarray_unary_op.py`
        - [x] `test_reduction.py`
        - [x] `test_scan.py`
            - depends on `inclusive_scan`
        - [x] `test_userkernel.py`
    - [x] `creation_tests`
        - [x] `test_basic.py`
        - [x] `test_from_data.py`
            - related: #4
        - [x] `test_matrix.py`
        - [x] `test_ranges.py`
    - [x] `ext_tests`
    - [x] `indexing_tests`
        - [x] `test_generate.py`
            - depends on `inclusive_scan` which is not ported to OpenCL
        - [x] `test_indexing.py`
            - depends on `ndarray.choose` which is not implemented on current ClPy
        - [x] `test_insert.py`
    - [x] `io_tests`
    - [ ] `linalg_tests`
        - depends on cusolver
    - [x] `logic_tests`
        - [x] `test_comparison.py`
        - [x] `test_content.py`
            - consists of tests using `half` .
        - [x] `test_ops.py`
        - [x] `test_truth.py`
            - some tests contain test data with `half` .
        - [x] `test_type_test.py`
    - [x] `manipulation_tests`
        - [x] `test_add_remove.py`
        - [x] `test_basic.py`
            - related: #4 
        - [x] `test_dims.py`
        - [x] `test_join.py`
        - [x] `test_kind.py`
        - [x] `test_rearrange.py`
        - [x] `test_shape.py`
        - [x] `test_split.py`
        - [x] `test_tiling.py`
        - [x] `test_transpose.py`
    - [x] `math_tests`
        - many tests contain test data with `half` , but ClPy doesn't support `half` .
    - [x] `opencl_tests`
    - [x] `padding_tests`
    - [ ] `prof_tests`
        - depebds on nvtx
    - [ ] `random_tests`
        - related: #28 
    - [ ] `sorting_tests`
        - [x] `test_count.py`
        - [x] `test_search.py`
            - depends on `inclusive_scan` which is not ported to OpenCL
        - [ ] `test_sort.py`
    - [ ] `sparse_tests`
    - [x] `statics_tests`
        - [x] `test_correlation.py`
        - [x] `test_histogram.py`
            - `half`, `atomicAdd` for int32(#30)
        - [x] `test_meanvar.py`
            - depends on `clpy.core.core._var`
        - [x] `test_order.py`
    - [x] `testing_tests`
- [ ] `example_tests`
- [x] `install_tests`

**Comment by vorj** [comment]
Some tests depend on [`inclusive_scan`](https://github.com/fixstars/clpy/blob/eb17d3a0f0222efb410f140ff19ec653d74284b7/clpy/core/core.pyx#L4247-L4283) which is not ported from CUDA C++ to OpenCL C in current ClPy. We should port it.

**Comment by LWisteria** [comment]
Now indivisual tests are on each issues.
