### ISSUE TITLE
Pass clpy_tests/core_tests/test_function.py

### ISSUE THREAD

**Issue by ghost** [fixstars/clpy#71]
We should support, remove, or fix clpy_tests/core_tests/test_function.py
https://github.com/fixstars/clpy/blob/clpy/tests/clpy_tests/core_tests/test_function.py

**Comment by nsakabe-fixstars** [comment]
[compiler.compile_with_cache が無い](https://github.com/fixstars/clpy/blob/8ddcad4820365ac8e67d63a7e9f825a8c8aa755e/tests/clpy_tests/core_tests/test_function.py#L11)から、 `opencl.utility.CreateProgram` を叩くことになるけど、(引数の型の都合で) Pure Python からこれを叩くのは無理かも。CreateProgramの更なるwrapperが必要な可能性がある。

**Comment by ghost** [comment]
こちら取り組んでいます。カーネル書き換え中

**Comment by ghost** [comment]
#120 がマージされたので閉じます
