### ISSUE TITLE
Pass clpy_tests/core_tests/test_fusion.py

### ISSUE THREAD

**Issue by ghost** [fixstars/clpy#72]
We should support, remove, or fix clpy_tests/core_tests/test_fusion.py
https://github.com/fixstars/clpy/blob/clpy/tests/clpy_tests/core_tests/test_fusion.py

**Comment by ghost** [comment]
Related: https://github.com/fixstars/clpy/pull/118

**Comment by vorj** [comment]
- [ ] import from fusion
- [ ] fp32->fp16 conversion on GPU
- [ ] C++ constructor support
- [ ] revert `min_max_st` implementation to CuPy's one, and fix it for ultima
- [ ] fix fusion.py for ClPy
- [ ] fix reduction kernel generation
- [ ] suppress "assigning to const variable" test
- [ ] add `M_PI` to stub header
