### ISSUE TITLE
Pass clpy_tests/core_tests/test_ndarray_adv_indexing.py

### ISSUE THREAD

**Issue by ghost** [fixstars/clpy#73]
We should support, remove, or fix clpy_tests/core_tests/test_ndarray_adv_indexing.py
https://github.com/fixstars/clpy/blob/clpy/tests/clpy_tests/core_tests/test_ndarray_adv_indexing.py

**Comment by t-kitawaki** [comment]
depends on #61, inclusive_scan

**Comment by ghost** [comment]
~~以下を実装する(書き換える)~~ 済

* `clpy.core.core._inclusive_scan_kernel`
* `clpy.core.core._scatter_op` 系

**Comment by ghost** [comment]
* clpy.core.core._getitem_mask_single
* clpy.core.core._scatter_op_single w/ op=='update'

**Comment by ghost** [comment]
In test_ndarray_adv_indexing.py,
only TestArrayAdvancedIndexingVectorValue fails.

I guess `_scatter_update_kernel` (in core.pyx) doesn't work.

Getting view works:
```
clpy.arange(24).reshape(2,3,4).astype('int32')[:, [[0, 1], [2, 0]]]

->
[[[[ 0  1  2  3]
   [ 4  5  6  7]]

  [[ 8  9 10 11]
   [ 0  1  2  3]]]


 [[[12 13 14 15]
   [16 17 18 19]]

  [[20 21 22 23]
   [12 13 14 15]]]]
```

Setting doesn't work:
```
a = numpy.zeros(2*3*4).reshape(2,3,4).astype('int32')
a [slice(None), [[0, 1], [2, 0]] ] = numpy.arange(2 * 2 * 2 * 4).reshape(2, 2, 2, 4)

->
[[[12 13 14 15]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[28 29 30 31]
  [20 21 22 23]
  [24 25 26 27]]]


c = clpy.zeros(2*3*4).reshape(2,3,4).astype('int32')
c [slice(None), [[0, 1], [2, 0]] ] = clpy.arange(2 * 2 * 2 * 4).reshape(2, 2, 2, 4)

->
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]]]
```

aren't there some data race...?

**Comment by ghost** [comment]
#196 has been merged!
