### ISSUE TITLE
Pass clpy_tests/core_tests/test_ndarray_complex_ops.py

### ISSUE THREAD

**Issue by ghost** [fixstars/clpy#74]
We should support, remove, or fix clpy_tests/core_tests/test_ndarray_complex_ops.py
https://github.com/fixstars/clpy/blob/clpy/tests/clpy_tests/core_tests/test_ndarray_complex_ops.py

**Comment by t-kitawaki** [comment]
related: #29

**Comment by LWisteria** [comment]
@snsato Are you working on this issue? Please assign yourself and comment before starting to work.
e.g. https://github.com/fixstars/clpy/issues/91#issuecomment-422299281

**Comment by ghost** [comment]
`test_ndarray_complex_ops.py` seems to have been tested.

Can this issue be closed?

**Comment by LWisteria** [comment]
Yes. @snsato forgot. Thanks!
