### ISSUE TITLE
Pass clpy_tests/core_tests/test_userkernel.py

### ISSUE THREAD

**Issue by ghost** [fixstars/clpy#77]
We should support, remove, or fix clpy_tests/core_tests/test_userkernel.py
https://github.com/fixstars/clpy/blob/clpy/tests/clpy_tests/core_tests/test_userkernel.py

**Comment by ghost** [comment]
I'll try it.

**Comment by LWisteria** [comment]
@t-kitawaki #122 resolved this issue. Thanks!
