### ISSUE TITLE
Pass clpy_tests/indexing_tests/test_generate.py

### ISSUE THREAD

**Issue by ghost** [fixstars/clpy#79]
We should support, remove, or fix clpy_tests/indexing_tests/test_generate.py
https://github.com/fixstars/clpy/blob/clpy/tests/clpy_tests/indexing_tests/test_generate.py

**Comment by ghost** [comment]
[Numpy Indexing Routines](https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.indexing.html)
* `ix_`
* `r_`
* `c_`

**Comment by ghost** [comment]
after enabling `ix_`, `c_`, `r_` ...

[_inclusive_scan_kernel](https://github.com/fixstars/clpy/blob/clpy/clpy/core/core.pyx#L4250)
should be rewritten from CUDA to OpenCL-like
 -> #139

**Comment by snsato** [comment]
I try to solve this issue.

**Comment by LWisteria** [comment]
#168 fixed this issue. Thanks!
