### ISSUE TITLE
Fill ndarray with clEnqueueFillBuffer

### ISSUE THREAD

**Issue by LWisteria** [fixstars/clpy#8]
Current [ndarray.zeros()](https://github.com/fixstars/clpy/blob/dec25c342032617d61e6b71ad5836b16005cc29a/clpy/creation/basic.py#L147) and [ndarray.fill()](https://github.com/fixstars/clpy/blob/dec25c342032617d61e6b71ad5836b16005cc29a/clpy/core/core.pyx#L448) always use elementwise_copy.

Use [clEnqueueFillBuffer](https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clEnqueueFillBuffer.html) to increase performance.

**Comment by ghost** [comment]
`clEnqueueFillBuffer` を使うには:
* dtypeに応じた適切なデータパターンを生成して
* そのポインタとバイト数(`sizeof(dtype)`)を渡す

必要がある。

**Comment by ghost** [comment]
fill() だけ clEnqueueFillbuffer 版にしたところ、 `test_ndarray_indexing.py:test_setitem_partial_constant` だけ落ちるようになってしまったが、ずれかたが謎

```
x = array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])
y = array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])
```

[`test_setitem_partial_constant`](https://github.com/fixstars/clpy/blob/clpy/tests/clpy_tests/core_tests/test_ndarray_indexing.py#L131) here.
```
    def test_setitem_partial_constant(self, xp, dtype):
        a = xp.zeros((2, 3, 4), dtype=dtype)
        a[1, 1:3] = 1
        return a
```

添字 `[]` をとったときにバッファのビューみたいなのが作られて、そのなかでオフセットを考慮しないとこうなる…? cupy の fill はそういうことをしていない為納得いかない。( [cupy.memoryで良きに計らっている??](https://github.com/cupy/cupy/blob/master/cupy/core/core.pyx#L524) )

**Comment by ghost** [comment]
MemoryPointer.cl_mem_offset() というのができているのを見逃していました。

**Comment by ghost** [comment]
* nvidia ランタイムで fill するサイズが 2GiB を超えるとしぬ
* そもそも EnqueueFillBuffer を使うと早くなったのか?
    * _vega_ でパフォーマンス計測をしてみる: 1000回 `fill(42)`, 配列 1024\*2048\*1024
        * elementwisecopy `python fill.py  1.52s user 0.74s system 9% cpu 23.867 total`
        * Enqueue  `python fill.py  1.13s user 0.51s system 6% cpu 23.993 total`
    * _titanv_ でパフォーマンス計測: 1000回 `fill(42)`, 配列 1024\*1024\*1024
        * elementwisecopy `python fill.py  5.50s user 4.12s system 118% cpu 8.147 total`
        * Enqueue  `python fill.py  5.51s user 4.09s system 118% cpu 8.132 total`

**Comment by ghost** [comment]
@LWisteria 
というわけで、(nvidia ランタイムバグってるし、) [実際に動かしてみて](https://github.com/fixstars/clpy/compare/clpy...fixstars:b598a3a)も clEnqueueFillBuffer を使うことにそれほど意味がなさそうです。
如何しましょうか。

**Comment by LWisteria** [comment]
うーん・・・ではとりあえず「実装しない」で閉じることにします（ただしTODOは残したままにしておきます）
