### ISSUE TITLE
Pass clpy_tests/logic_tests/test_content.py

### ISSUE THREAD

**Issue by ghost** [fixstars/clpy#83]
We should support, remove, or fix clpy_tests/logic_tests/test_content.py
https://github.com/fixstars/clpy/blob/clpy/tests/clpy_tests/logic_tests/test_content.py

**Comment by ghost** [comment]
* `isnan`
* `isinf`
* `isfinite`
 -> https://github.com/fixstars/clpy/pull/131

**Comment by vorj** [comment]
After #131 will be merged, we can pass this test by purging unsupported features (half-float and complex) like [this](https://github.com/fixstars/clpy/compare/72-test_fusion_py...vorj:pass-some-tests).

**Comment by snsato** [comment]
clpy_tests/logic_tests/test_content.py passed pytest after https://github.com/fixstars/clpy/pull/131, and add jenkins TEST_FILE at https://github.com/fixstars/clpy/pull/167 .

**Comment by LWisteria** [comment]
@snsato I think this issue has completed. Can I close?

**Comment by snsato** [comment]
@LWisteria I think so, too. Please close this issue.

**Comment by LWisteria** [comment]
OK. Thank you all!
