### ISSUE TITLE
Meet flake8 on cython files

### ISSUE THREAD

**Issue by LWisteria** [fixstars/clpy#9]
Current clpy meet flake8 on only pure python files. Meet also on cython files to meet [cupy's coding guidelines](https://docs-cupy.chainer.org/en/stable/contribution.html#coding-guidelines)

**Comment by LWisteria** [comment]
@ykitta-fixstars Can you setup flake8 CI? You can use travis or internal jenkins or others you like.

**Comment by ghost** [comment]
OK.

**Comment by LWisteria** [comment]
Resolved by #17 and #26, thank you
