### ISSUE TITLE
Pass clpy_tests/manipulation_tests/test_rearrange.py

### ISSUE THREAD

**Issue by ghost** [fixstars/clpy#91]
We should support, remove, or fix clpy_tests/manipulation_tests/test_rearrange.py
https://github.com/fixstars/clpy/blob/clpy/tests/clpy_tests/manipulation_tests/test_rearrange.py

**Comment by ghost** [comment]
I'll try it.

**Comment by LWisteria** [comment]
#133 resolve this issue. thanks!
